objects/Account.object
<CustomObject>
    <fields>
        <fullName>Customer_Disc_Group__c</fullName>
        <description>This field is used to map discount and query from Discount Mapping object</description>
        <inlineHelpText>This is a Customer Discount Group</inlineHelpText>
        <label>Customer Disc. Group</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Order_Line_Item__c.object
<CustomObject>
    <fields>
        <fullName>CGST__c</fullName>
        <description>This Field store CGST Price (Price After Discount * CGST%)</description>
        <label>CGST</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Cash_Discount_CD__c</fullName>
        <description>This Field store Cash Discount ((Quantity*Unit Price)*Cash Discount %</description>
        <label>Cash Discount(CD)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Cash_Discount_Percentage__c</fullName>
        <label>Cash Discount Percentage</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Final_Price__c</fullName>
        <description>This Field store Final Price ((Quantity*Unit Price)-Total Discount )+CGST+SGST</description>
        <label>Final Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>OriPlast_Product_Unit_Price__c</fullName>
        <description>This field fetch Unit Price from related product</description>
        <formula>OriPlast_Product_Price__r.Unit_Price__c</formula>
        <label>OriPlast Product Unit Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Ori_Plast_Order__c</fullName>
        <description>Lookup with Ori-plast Order</description>
        <label>Ori-Plast Order</label>
        <referenceTo>Ori_Plast_Order__c</referenceTo>
        <relationshipLabel>Order-Line-Items</relationshipLabel>
        <relationshipName>Order_Line_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Ori_Plast_Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup with Ori-plast Product</description>
        <label>Ori-Plast Product</label>
        <referenceTo>OriPlast_Product__c</referenceTo>
        <relationshipLabel>Order-Line-Items</relationshipLabel>
        <relationshipName>Order_Line_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Price_After_Discount__c</fullName>
        <description>This Field store After Discount Price ((Quantity*Unit Price)-Trade Discount - Cash Discount)</description>
        <label>Price After Discount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Quantity__c</fullName>
        <description>This is for Product quantity</description>
        <label>Quantity</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>SGST__c</fullName>
        <description>This Field store SGST price (Price After Discount * SGST%)</description>
        <label>SGST</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Special_Discount__c</fullName>
        <label>Special Discount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Total_Price__c</fullName>
        <description>This Field store Total Price (Quantity*Unit Price)</description>
        <formula>OriPlast_Product_Price__r.Unit_Price__c *  ERP_Quantity__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Total Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Trade_Discount_TD_After_Shipment__c</fullName>
        <label>Trade Discount(TD) After Shipment</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Trade_Discount_TD__c</fullName>
        <description>This Field store Trade Discount ((Quantity*Unit Price)*Trade Discount %)</description>
        <label>Trade Discount(TD)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Trade_Discount__c</fullName>
        <description>This Field store Trade Discount for A Product from Discount Mapping Obj. by flow</description>
        <label>Trade Discount</label>
        <precision>5</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Unit_of_Measure__c</fullName>
        <label>Unit of Measure</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Order-Line-Item</label>
    <nameField>
        <displayFormat>OLN-{000000}</displayFormat>
        <label>Order-Line-Item No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Order-Line-Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Ori_Plast_Order__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <description>Ori-plast product Supplier</description>
        <inlineHelpText>The distributor account that generated the sales order.</inlineHelpText>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Ori-Plast Orders</relationshipLabel>
        <relationshipName>Ori_Plast_Orders</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Order_Status__c</fullName>
        <description>This field state different stage of orders</description>
        <inlineHelpText>Order Status indicates various order stages.</inlineHelpText>
        <label>Order Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                    <color>#FF9900</color>
                    <default>true</default>
                    <label>Draft</label>
                </value>
                <value>
                    <fullName>Submitted</fullName>
                    <color>#33FFFF</color>
                    <label>Submitted</label>
                </value>
                <value>
                    <fullName>Received by Navision</fullName>
                    <color>#66FF99</color>
                    <label>Received by Business Central</label>
                </value>
                <value>
                    <fullName>Partially Delivered</fullName>
                    <color>#66CCCC</color>
                    <label>Partially Delivered</label>
                </value>
                <value>
                    <fullName>Delivered</fullName>
                    <color>#33CC00</color>
                    <label>Delivered</label>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                    <isActive>false</isActive>
                    <label>Cancelled</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Ori-Plast Order</label>
    <nameField>
        <displayFormat>ON-26-27-{000000}</displayFormat>
        <label>Ori-Plast Order No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Ori-Plast Orders</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/OriPlast_Discount_Mapping__c.object
<CustomObject>
    <fields>
        <fullName>Cash_Discount__c</fullName>
        <description>This Field Store Cash Discount For a Product</description>
        <label>Cash Discount %</label>
        <precision>6</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Discount__c</fullName>
        <description>This field stored TD For a product</description>
        <label>Trade Discount (TD) %</label>
        <precision>5</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>ItemDiscountCode_ExternalKey__c</fullName>
        <caseSensitive>true</caseSensitive>
        <description>This Field Store combined Value of (Account.Customer Disc. Group_Product.Item Disc. Group)</description>
        <externalId>true</externalId>
        <label>ItemDiscountCode_ExternalKey</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Line_Discount__c</fullName>
        <label>Line Discount %</label>
        <precision>6</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Special_Discount__c</fullName>
        <description>This field made for if in future there are special discount for a product</description>
        <label>Special Discount %</label>
        <precision>6</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <label>OriPlast Discount Mapping</label>
    <nameField>
        <label>Discount Maping Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>OriPlast Discount Mappings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/OriPlast_Product__c.object
<CustomObject>
    <fields>
        <fullName>GST_Value__c</fullName>
        <description>This Field is used to calculate GST on flow</description>
        <formula>IF( GST_Group_Code__c  = &quot;G18.00&quot;, 18,  IF(GST_Group_Code__c  = &quot;G05.00&quot;, 5, 00) )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>GST Value</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Item_Disc_Group__c</fullName>
        <description>Here the discounts are defined for specific items or item groups.</description>
        <inlineHelpText>It is used for entering Item Discount Group</inlineHelpText>
        <label>Item Disc. Group</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Length_In_Meter__c</fullName>
        <description>This field will display the length of the product in meter</description>
        <formula>TEXT(VALUE(Length__c)/10)</formula>
        <label>Length (Meter)</label>
        <type>Text</type>
    </fields>
    <label>Ori-Plast Product</label>
    <nameField>
        <label>Ori-PlastProduct Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Ori-Plast Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/OriPlastDiscountBatch.cls
/*
 * Pratik Mondal
 * Created on - 24-02-2026
 * ---------------------
 * This batch class processes Draft Ori-Plast Orders and calculates Trade Discount,
 * Cash Discount, GST (CGST & SGST), and Final Price for related Order Line Items.
 * It dynamically derives discount mappings using Customer & Item Discount Groups
 */

global class OriPlastDiscountBatch implements Database.Batchable<SObject> {

  
    // START METHOD
   
    global Database.QueryLocator start(Database.BatchableContext bc) {
        return Database.getQueryLocator(
            [
                SELECT Id, Account__c
                FROM Ori_Plast_Order__c
                WHERE Order_Status__c = 'Draft'
            ]
        );
    }

   
    // EXECUTE METHOD
    
    global void execute(Database.BatchableContext bc, List<Ori_Plast_Order__c> scopeOrders) {

        if(scopeOrders.isEmpty()) return;

        Set<Id> orderIds = new Set<Id>();
        Set<Id> accountIds = new Set<Id>();
        Map<Id, Ori_Plast_Order__c> orderMap = new Map<Id, Ori_Plast_Order__c>();

        for(Ori_Plast_Order__c ord : scopeOrders){
            orderIds.add(ord.Id);
            accountIds.add(ord.Account__c);
            orderMap.put(ord.Id, ord);
        }

       
       //  Fetch Accounts
     
        Map<Id, Account> accMap = new Map<Id, Account>(
            [
                SELECT Id, Customer_Disc_Group__c
                FROM Account
                WHERE Id IN :accountIds
            ]
        );

       
      //   Fetch Order Line Items
       
        List<Order_Line_Item__c> lineItems = [
            SELECT Id,
                   Ori_Plast_Order__c,
                   Ori_Plast_Product__c,
                   Quantity__c,
                   Total_Price__c,
                   Cash_Discount_CD__c,
                   Unit_of_Measure__c,
                   OriPlast_Product_Unit_Price__c
            FROM Order_Line_Item__c
            WHERE Ori_Plast_Order__c IN :orderIds
        ];

        if(lineItems.isEmpty()) return;

      
        // Collect Product Ids
     
        Set<Id> productIds = new Set<Id>();
        for(Order_Line_Item__c oli : lineItems){
            if(oli.Ori_Plast_Product__c != null){
                productIds.add(oli.Ori_Plast_Product__c);
            }
        }

      
       //  Fetch Products 
     
        Map<Id, OriPlast_Product__c> productMap = new Map<Id, OriPlast_Product__c>(
            [
                SELECT Id,
                       Item_Disc_Group__c,
                       Length_In_Meter__c,
                       GST_Value__c
                FROM OriPlast_Product__c
                WHERE Id IN :productIds
            ]
        );


       //  Prepare Discount Keys
      
        Set<String> discountKeys = new Set<String>();

        for(Order_Line_Item__c oli : lineItems){

            Ori_Plast_Order__c ord = orderMap.get(oli.Ori_Plast_Order__c);
            Account acc = accMap.get(ord.Account__c);
            OriPlast_Product__c prod = productMap.get(oli.Ori_Plast_Product__c);

            if(acc == null || prod == null) continue;

            if(String.isBlank(acc.Customer_Disc_Group__c) ||
               String.isBlank(prod.Item_Disc_Group__c)) continue;

            String key = acc.Customer_Disc_Group__c + '_' + prod.Item_Disc_Group__c;
            discountKeys.add(key);
        }

        
         //Fetch Discount Mapping
        
        Map<String, OriPlast_Discount_Mapping__c> discountMap =
            new Map<String, OriPlast_Discount_Mapping__c>();

        for(OriPlast_Discount_Mapping__c dm : [
            SELECT ItemDiscountCode_ExternalKey__c,
                   Discount__c,
                   Special_Discount__c,
                   Line_Discount__c,
                   Cash_Discount__c
            FROM OriPlast_Discount_Mapping__c
            WHERE ItemDiscountCode_ExternalKey__c IN :discountKeys
        ]){
            discountMap.put(dm.ItemDiscountCode_ExternalKey__c, dm);
        }

        
          //calculation logic
      
        List<Order_Line_Item__c> updateList = new List<Order_Line_Item__c>();

        for(Order_Line_Item__c oli : lineItems){

            Ori_Plast_Order__c ord = orderMap.get(oli.Ori_Plast_Order__c);
            Account acc = accMap.get(ord.Account__c);
            OriPlast_Product__c prod = productMap.get(oli.Ori_Plast_Product__c);

            if(acc == null || prod == null) continue;
            if(String.isBlank(acc.Customer_Disc_Group__c) ||
               String.isBlank(prod.Item_Disc_Group__c)) continue;

            String key = acc.Customer_Disc_Group__c + '_' + prod.Item_Disc_Group__c;
            if(!discountMap.containsKey(key)) continue;

            OriPlast_Discount_Mapping__c disc = discountMap.get(key);

            Decimal quantity = oli.Quantity__c == null ? 0 : oli.Quantity__c;
            Decimal unitPrice = oli.OriPlast_Product_Unit_Price__c == null ? 0 : oli.OriPlast_Product_Unit_Price__c;

            // Base Price Calculation 
            Decimal basePrice;

            if(oli.Unit_of_Measure__c == 'MTR'){
                Decimal length = 1;
                if(!String.isBlank(prod.Length_In_Meter__c)){
                    try{
                        length = Decimal.valueOf(prod.Length_In_Meter__c);
                    }catch(Exception e){
                        length = 1;
                    }
                }
                basePrice = unitPrice * quantity * length;
            } else {
                basePrice = unitPrice * quantity;
            }

            // Trade Discount 
            Decimal tradePercent =
                (disc.Discount__c == null ? 0 : disc.Discount__c) +
                (disc.Special_Discount__c == null ? 0 : disc.Special_Discount__c);

            Decimal tradeAmount = basePrice * tradePercent / 100;
            Decimal tradeAfter = basePrice - tradeAmount;

            Decimal tradeDiscountAmount = disc.Discount__c * oli.Total_Price__c / 100;

            // Cash Discount 
            Decimal cashPercent = disc.Cash_Discount__c == null ? 0 : disc.Cash_Discount__c;
            Decimal cashAmount = tradeAfter * cashPercent / 100;

            Decimal priceAfterDiscount = tradeAfter - cashAmount;

            
              // GST CALCULATION
             
            Decimal gstPercent = prod.GST_Value__c == null ? 0 : prod.GST_Value__c;
            Decimal gstAmount = priceAfterDiscount * gstPercent / 100;
           
            Decimal cgst = gstAmount / 2;
            Decimal sgst = gstAmount / 2;
            

            Decimal finalPriceWithGST = priceAfterDiscount + gstAmount;

            //Update fields
            oli.Trade_Discount__c = disc.Discount__c;
            oli.Cash_Discount_Percentage__c = disc.Cash_Discount__c;
            oli.Trade_Discount_TD_After_Shipment__c = tradeAfter;
            oli.Price_After_Discount__c = priceAfterDiscount;
            oli.Cash_Discount_CD__c = cashAmount;
            oli.Trade_Discount_TD__c = tradeDiscountAmount;

            // GST Fields 
            oli.CGST__c = cgst;
            oli.SGST__c = sgst;
            oli.Final_Price__c = finalPriceWithGST;
           

            updateList.add(oli);
        }

        if(!updateList.isEmpty()){
            update updateList;
        }
    }

    
      // Finish method
 
    global void finish(Database.BatchableContext bc){
        System.debug('OriPlast Discount + GST Batch Completed Successfully');
    }
}