objects/Account.object
<CustomObject>
    <fields>
        <fullName>Associated_User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field is used to get related User</description>
        <inlineHelpText>This is for an associated user field</inlineHelpText>
        <label>Associated User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Invoice__c.object
<CustomObject>
    <fields>
        <fullName>Dealer_Name__c</fullName>
        <description>This is the text field getting value from JSON Data of the Staging Record</description>
        <label>Dealer Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Distributor__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Distributor</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Invoices (Distributor)</relationshipLabel>
        <relationshipName>Invoices</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Invoice_Date__c</fullName>
        <label>Invoice Date Text</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Invoice_Number__c</fullName>
        <description>External unique Id coming from JSON.</description>
        <label>Invoice Number</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>Invoice</label>
    <nameField>
        <displayFormat>INV-{000000}</displayFormat>
        <label>Invoice Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Invoice_Line_Item__c.object
<CustomObject>
    <fields>
        <fullName>Final_Price__c</fullName>
        <description>This Field store Final Price from Integration</description>
        <label>Final Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Invoice_No__c</fullName>
        <description>This Field store Invoice No. from Integration</description>
        <externalId>true</externalId>
        <label>Invoice No.</label>
        <length>250</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Ori_Plast_Invoice__c</fullName>
        <label>Ori-Plast Invoice</label>
        <referenceTo>Invoice__c</referenceTo>
        <relationshipName>Ori_plast_Invoice_Line_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Ori_Plast_Product_Name__c</fullName>
        <description>This Field is used to show Ori-Plast Product name</description>
        <formula>Ori_Plast_Product__r.Name</formula>
        <label>Ori-Plast Product Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Ori_Plast_Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Ori-Plast Product</label>
        <referenceTo>OriPlast_Product__c</referenceTo>
        <relationshipName>Ori_plast_Invoice_Line_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Quantity__c</fullName>
        <description>This Field store Quantity from Integration</description>
        <label>Quantity</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>SKU__c</fullName>
        <label>Item Description</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Unit_of_Measure__c</fullName>
        <description>This Field store Unit of Measure from Integration</description>
        <label>UOM</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>Invoice Line Item</label>
    <nameField>
        <displayFormat>ILN-{0000000}</displayFormat>
        <label>Invoice-Line-Item No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoice Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/OriPlast_Product__c.object
<CustomObject>
    <fields>
        <fullName>Category_Picklist__c</fullName>
        <description>This is a picklist field for choosing type of Category for the customers who search for products.</description>
        <inlineHelpText>This is a picklist field for choosing type of category.</inlineHelpText>
        <label>Category</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>P1</fullName>
                    <label>PVC Pipe ASTM-D-1785, PVC ASTM (Schdule)</label>
                </value>
                <value>
                    <fullName>P2</fullName>
                    <label>PVC Grey pipes as per IS : 4985,UPVC IS 4985</label>
                </value>
                <value>
                    <fullName>P3</fullName>
                    <label>CASING &amp; PVC Casing Pipes as per IS : 12818</label>
                </value>
                <value>
                    <fullName>P4</fullName>
                    <label>PVC SCREEN &amp; PVC Screen Pipes as per IS : 12818</label>
                </value>
                <value>
                    <fullName>P5</fullName>
                    <label>PVC GARDEN HOSE PIPE</label>
                </value>
                <value>
                    <fullName>P6</fullName>
                    <label>PVC SWR pipes &amp; fittings as per IS:13592</label>
                </value>
                <value>
                    <fullName>P7</fullName>
                    <label>PVC Column Pipe</label>
                </value>
                <value>
                    <fullName>P8</fullName>
                    <label>PVC Submersible</label>
                </value>
                <value>
                    <fullName>P9</fullName>
                    <label>CPVC Pipe</label>
                </value>
                <value>
                    <fullName>PF</fullName>
                    <label>PVC Fittings</label>
                </value>
                <value>
                    <fullName>H1</fullName>
                    <label>HDPE Pipe IS 4984 (Black)</label>
                </value>
                <value>
                    <fullName>H2</fullName>
                    <label>HDPE Pipe IS 14333 (Black)</label>
                </value>
                <value>
                    <fullName>H3</fullName>
                    <label>GI STANDERD &amp; PLB Duct Pipe</label>
                </value>
                <value>
                    <fullName>H4</fullName>
                    <label>HDPE IS 4427 (Blue/Black)</label>
                </value>
                <value>
                    <fullName>H5</fullName>
                    <label>HDPE 4984-2016</label>
                </value>
                <value>
                    <fullName>HF</fullName>
                    <label>HDPE Fittings</label>
                </value>
                <value>
                    <fullName>DF</fullName>
                    <label>Direct Action Hand Pump Fittings</label>
                </value>
                <value>
                    <fullName>M1</fullName>
                    <label>MDPE Pipe &amp; MDPE IS 14885</label>
                </value>
                <value>
                    <fullName>M2</fullName>
                    <label>MDPE pipe &amp; MDPE IS 4427</label>
                </value>
                <value>
                    <fullName>SL</fullName>
                    <label>Solvent Cement</label>
                </value>
                <value>
                    <fullName>NI</fullName>
                    <label>PVC SWR pipes &amp; fittings (non-standard)</label>
                </value>
                <value>
                    <fullName>DP</fullName>
                    <label>Direct Action Hand Pump Set</label>
                </value>
                <value>
                    <fullName>H6</fullName>
                    <label>PPR</label>
                </value>
                <value>
                    <fullName>H7</fullName>
                    <label>HDPE Copper Wire</label>
                </value>
                <value>
                    <fullName>M3</fullName>
                    <label>PE PIPE(MDPE)</label>
                </value>
                <value>
                    <fullName>MF</fullName>
                    <label>MDPE Fittings</label>
                </value>
                <value>
                    <fullName>OF</fullName>
                    <label>OPVC Fittings</label>
                </value>
                <value>
                    <fullName>OP</fullName>
                    <label>OPVC Pipe</label>
                </value>
                <value>
                    <fullName>WT</fullName>
                    <label>WATER TANK and FITTINGS</label>
                </value>
                <value>
                    <fullName>TW</fullName>
                    <isActive>false</isActive>
                    <label>ASTM-D 1785 Push type White, Solvent Ciment Type</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Sub_Category_Picklist__c</fullName>
        <description>This is kind of picklist for choosing Sub Category of a product that is nested in another category.</description>
        <inlineHelpText>It is used for choosing Sub Category of a product.</inlineHelpText>
        <label>Sub Category</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Category_Picklist__c</controllingField>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>ASTM</fullName>
                </value>
                <value>
                    <fullName>CLASS1 (SDR11)</fullName>
                </value>
                <value>
                    <fullName>ISO 4427 Fittings</fullName>
                </value>
                <value>
                    <fullName>Male Thread</fullName>
                </value>
                <value>
                    <fullName>Pipe Grade PE 63</fullName>
                </value>
                <value>
                    <fullName>SDR 41</fullName>
                </value>
                <value>
                    <fullName>Single Socket</fullName>
                </value>
                <value>
                    <fullName>Pipe Grade PE 80</fullName>
                </value>
                <value>
                    <fullName>SDR 33</fullName>
                </value>
                <value>
                    <fullName>Bell End</fullName>
                </value>
                <value>
                    <fullName>CLASS2 (SDR 13.5)</fullName>
                </value>
                <value>
                    <fullName>Double Socket</fullName>
                </value>
                <value>
                    <fullName>IS 14333 Fittings</fullName>
                </value>
                <value>
                    <fullName>Male / Female Thread</fullName>
                </value>
                <value>
                    <fullName>UPVC</fullName>
                </value>
                <value>
                    <fullName>SDR 26</fullName>
                </value>
                <value>
                    <fullName>Pipe Grade PE 100</fullName>
                </value>
                <value>
                    <fullName>Plain End</fullName>
                </value>
                <value>
                    <fullName>Push Type</fullName>
                </value>
                <value>
                    <fullName>Sliding Socket</fullName>
                </value>
                <value>
                    <fullName>SWR</fullName>
                </value>
                <value>
                    <fullName>SDR 21</fullName>
                </value>
                <value>
                    <fullName>Cam Lock</fullName>
                </value>
                <value>
                    <fullName>CPVC</fullName>
                </value>
                <value>
                    <fullName>Flush Joint</fullName>
                </value>
                <value>
                    <fullName>SDR 17</fullName>
                </value>
                <value>
                    <fullName>LED &amp; TIN FREE</fullName>
                </value>
                <value>
                    <fullName>SDR 13.6</fullName>
                </value>
                <value>
                    <fullName>SDR 11</fullName>
                </value>
                <value>
                    <fullName>SDR 9</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Ori-Plast Product</label>
    <nameField>
        <label>Ori-PlastProduct Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Ori-Plast Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/WeeklyInvoiceLineItemExcelBatch.cls
global class WeeklyInvoiceLineItemExcelBatch implements Database.Batchable<SObject>, Database.Stateful {
    
    // Map: DistributorId -> List of rows (each row is a List<String> of column values)
    private Map<Id, List<List<String>>> distributorRows = new Map<Id, List<List<String>>>();
    
    // Week boundaries used in the query (computed once at construction)
    private Datetime startDateTime;
    private Datetime endDateTime;
    
    // Constructor: compute current week's Monday..Sunday (week starts Monday)
    public WeeklyInvoiceLineItemExcelBatch() {
        Date startOfWeek = Date.today().toStartOfWeek();
        Date endOfWeek   = startOfWeek.addDays(6);
        
        this.startDateTime = Datetime.newInstance(startOfWeek, Time.newInstance(0,0,0,0));
        this.endDateTime   = Datetime.newInstance(endOfWeek, Time.newInstance(23,59,59,999));
        
    }
    
    // Start: query Invoice_Line_Item__c for the week's invoices (pull required parent fields)
    global Database.QueryLocator start(Database.BatchableContext bc) {
        return Database.getQueryLocator(
            [SELECT Name, Invoice_No__c, SKU__c, Ori_Plast_Product_Name__c, Quantity__c, Final_Price__c,
                Ori_Plast_Invoice__r.Id, Ori_Plast_Invoice__r.Invoice_Number__c, Ori_Plast_Invoice__r.Name,
                Ori_Plast_Invoice__r.Invoice_Date__c, Ori_Plast_Invoice__r.CreatedDate, Ori_Plast_Invoice__r.Distributor__c,
                Ori_Plast_Invoice__r.Distributor__r.Name, Ori_Plast_Invoice__r.Dealer_Name__c,
                Ori_Plast_Product__r.Sub_Category_Picklist__c, Ori_Plast_Product__r.Category_Picklist__c, Unit_of_Measure__c
         FROM Invoice_Line_Item__c
         WHERE Ori_Plast_Invoice__r.CreatedDate >= :startDateTime
           AND Ori_Plast_Invoice__r.CreatedDate <= :endDateTime
         ORDER BY Ori_Plast_Invoice__r.CreatedDate DESC]
            );
    }
    
    
    // Execute: group rows by Distributor Id. Keep only strings to reduce memory usage.
    global void execute(Database.BatchableContext bc, List<SObject> scope) {
        for (SObject s : scope) {
            Invoice_Line_Item__c line = (Invoice_Line_Item__c)s;
            // Defensive: ensure parent invoice and distributor exist
            if (line.Ori_Plast_Invoice__r == null || line.Ori_Plast_Invoice__r.Distributor__c == null) {
                continue;
            }
            Id distributorId = line.Ori_Plast_Invoice__r.Distributor__c;
            
            // Prepare row: match the columns you requested earlier
            List<String> row = new List<String>{
                safeString(line.Name),
                safeString(line.Invoice_No__c),
                safeString(line.Ori_Plast_Invoice__r.Invoice_Number__c),
                safeString(line.Ori_Plast_Invoice__r.Name),
                safeString(line.Ori_Plast_Invoice__r.Invoice_Date__c),
                String.valueOf(line.Ori_Plast_Invoice__r.CreatedDate),
                safeString(line.Ori_Plast_Invoice__r.Distributor__r != null ? line.Ori_Plast_Invoice__r.Distributor__r.Name : null),
                safeString(line.Ori_Plast_Invoice__r.Dealer_Name__c),
                safeString(line.Ori_Plast_Product_Name__c),
                safeString(line.SKU__c),
                safeString(line.Ori_Plast_Product__r != null ? line.Ori_Plast_Product__r.Sub_Category_Picklist__c : null),
                safeString(line.Ori_Plast_Product__r != null ? line.Ori_Plast_Product__r.Category_Picklist__c : null),
                safeString(line.Unit_of_Measure__c),
                safeString(line.Quantity__c),
                safeString(line.Final_Price__c)
            };
            
            if (!distributorRows.containsKey(distributorId)) {
                distributorRows.put(distributorId, new List<List<String>>());
            }
            distributorRows.get(distributorId).add(row);
        }
    }
    
    // Finish: for each distributor build an Excel XML workbook (one worksheet) and email to Associated_User__c email
    global void finish(Database.BatchableContext bc) {
        
        if (distributorRows.isEmpty()) {
            System.debug('No invoice line items found for the week ' + startDateTime + ' - ' + endDateTime);
            return;
        }
        
        // Query Accounts to get Associated_User__c -> then User email
        Set<Id> distributorIds = distributorRows.keySet();
        Map<Id, Account> accMap = new Map<Id, Account>(
            [SELECT Id, Name, Associated_User__c, Associated_User__r.Email FROM Account WHERE Id IN :distributorIds]
            );
        
        // For each distributor, build XML and send email to the associated user
        for (Id distId : distributorRows.keySet()) {
            Account acc = accMap.get(distId);
            if (acc == null) {
                System.debug('No Account found for distributor id: ' + distId);
                continue;
            }
            
            String recipientEmail;
            if (acc.Associated_User__c != null && acc.Associated_User__r != null) {
                recipientEmail = acc.Associated_User__r.Email;
            }
            if (String.isBlank(recipientEmail)) {
                System.debug('No associated user email for Distributor: ' + acc.Name + ' (' + acc.Id + '), skipping email.');
                continue;
            }
            
            // Build Excel (XML Spreadsheet) content for this distributor
            String xml = buildExcelForDistributor(acc.Name, distributorRows.get(distId));
            
            // Create attachment
            Blob excelBlob = Blob.valueOf(xml);
            Messaging.EmailFileAttachment efa = new Messaging.EmailFileAttachment();
            String safeFileName = sanitizeFileName(acc.Name) + '_Invoices_' +
                startDateTime.date().format() + '_to_' + endDateTime.date().format() + '.xls';
            efa.setFileName(safeFileName);
            efa.setBody(excelBlob);
            efa.setContentType('application/vnd.ms-excel');
            
            // Prepare email
            Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
            // mail.setToAddresses(new String[]{recipientEmail});
            mail.setToAddresses(new String[] { 'ayantika_c@pursuitsoftware.com' });
            mail.setSubject('Weekly Invoice Line Items for ' + acc.Name + ' (' + startDateTime.date().format() + ' - ' + endDateTime.date().format() + ')');
            mail.setPlainTextBody('Please find attached the weekly invoice line items.');
            mail.setFileAttachments(new Messaging.EmailFileAttachment[]{efa});
            
            try {
                Messaging.sendEmail(new Messaging.SingleEmailMessage[]{mail});
                System.debug('Sent weekly invoice file to ' + recipientEmail + ' for distributor ' + acc.Name);
            } catch (Exception ex) {
                System.debug('Failed to send email to ' + recipientEmail + ' : ' + ex.getMessage());
            }
        }
    }
    
    // -----------------------
    // Helper methods
    // -----------------------
    
    // Build Excel XML for a distributor - single worksheet per distributor
    private String buildExcelForDistributor(String distributorName, List<List<String>> rows) {
        String excelStart =
            '<?xml version="1.0"?>' +
            '<?mso-application progid="Excel.Sheet"?>' +
            '<Workbook xmlns="urn:schemas-microsoft-com:office:spreadsheet"' +
            ' xmlns:o="urn:schemas-microsoft-com:office:office"' +
            ' xmlns:x="urn:schemas-microsoft-com:office:excel"' +
            ' xmlns:ss="urn:schemas-microsoft-com:office:spreadsheet"' +
            ' xmlns:html="http://www.w3.org/TR/REC-html40">';
        String excelEnd = '</Workbook>';
        
        String sheetName = sanitizeSheetName(distributorName);
        String sheet = '<Worksheet ss:Name="' + sheetName + '"><Table>';
        // Header row - same columns as we stored
        List<String> headers = new List<String>{
            'LineItem.Name','LineItem.Invoice_No__c','Invoice.Invoice_Number__c','Invoice.Name','Invoice.Invoice_Date__c',
            'Invoice.CreatedDate','Distributor.Name','Dealer_Name__c','Ori_Plast_Product_Name__c','SKU__c',
            'Product.Sub_Category','Product.Category','Unit_of_Measure__c','Quantity__c','Final_Price__c'
        };
        
        sheet += '<Row>';
        for (String h : headers) {
            sheet += '<Cell><Data ss:Type="String">' + escapeXml(h) + '</Data></Cell>';
        }
        sheet += '</Row>';
        
        // Data rows
        for (List<String> row : rows) {
            sheet += '<Row>';
            for (String col : row) {
                // determine type: we keep everything as String to avoid parsing hassles
                sheet += '<Cell><Data ss:Type="String">' + escapeXml(col) + '</Data></Cell>';
            }
            sheet += '</Row>';
        }
        
        sheet += '</Table></Worksheet>';
        return excelStart + sheet + excelEnd;
    }
    
    // Safe conversion to string; handle nulls and numbers
    private String safeString(Object o) {
        if (o == null) return '';
        try {
            return String.valueOf(o);
        } catch (Exception ex) {
            return '';
        }
    }
    
    // Escape minimal XML characters in cell values
    private String escapeXml(String s) {
        if (s == null) return '';
        s = s.replace('&', '&amp;');
        s = s.replace('<', '&lt;');
        s = s.replace('>', '&gt;');
        s = s.replace('"', '&quot;');
        // s = s.replace("'", '&apos;');
        return s;
    }
    
    // Sanitize worksheet name (Excel limit 31 chars and forbids certain chars)
    private String sanitizeSheetName(String name) {
        if (String.isBlank(name)) name = 'Sheet';
        
        String out = name;
        
        // Replace forbidden Excel sheet name characters : \ / ? * [ ]
        out = out.replace(':', ' ');
        out = out.replace('\\', ' ');
        out = out.replace('/', ' ');
        out = out.replace('?', ' ');
        out = out.replace('*', ' ');
        out = out.replace('[', ' ');
        out = out.replace(']', ' ');
        
        out = out.trim();
        if (out.length() > 30) out = out.substring(0, 30);
        
        return escapeXml(out);
    }
    
    
    // Sanitize filename for attachment
    private String sanitizeFileName(String name) {
        if (String.isBlank(name)) name = 'Distributor';
        
        String out = name;
        
        // Regex-safe replacement of invalid filename characters
        out = out.replaceAll('[\\\\/:*?\"<>|]', '_');
        
        if (out.length() > 40) out = out.substring(0, 40);
        
        return out;
    }
}