objects/Account.object
<CustomObject>
    <fields>
        <fullName>Customer_Disc_Group__c</fullName>
        <description>This field is used to map discount and query from Discount Mapping object</description>
        <inlineHelpText>This is a Customer Discount Group</inlineHelpText>
        <label>Customer Disc. Group</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Order_Line_Item__c.object
<CustomObject>
    <fields>
        <fullName>Ori_Plast_Order__c</fullName>
        <description>Lookup with Ori-plast Order</description>
        <label>Ori-Plast Order</label>
        <referenceTo>Ori_Plast_Order__c</referenceTo>
        <relationshipLabel>Order-Line-Items</relationshipLabel>
        <relationshipName>Order_Line_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Ori_Plast_Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup with Ori-plast Product</description>
        <label>Ori-Plast Product</label>
        <referenceTo>OriPlast_Product__c</referenceTo>
        <relationshipLabel>Order-Line-Items</relationshipLabel>
        <relationshipName>Order_Line_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Order-Line-Item</label>
    <nameField>
        <displayFormat>OLN-{000000}</displayFormat>
        <label>Order-Line-Item No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Order-Line-Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Ori_Plast_Order__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <description>Ori-plast product Supplier</description>
        <inlineHelpText>The distributor account that generated the sales order.</inlineHelpText>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Ori-Plast Orders</relationshipLabel>
        <relationshipName>Ori_Plast_Orders</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Ori-Plast Order</label>
    <nameField>
        <displayFormat>ON-26-27-{000000}</displayFormat>
        <label>Ori-Plast Order No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Ori-Plast Orders</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/OriPlast_Discount_Mapping__c.object
<CustomObject>
    <fields>
        <fullName>Starting_Date__c</fullName>
        <description>This Field Store Starting Date From Product to Product Price</description>
        <label>Starting Date</label>
        <type>Date</type>
    </fields>
    <label>OriPlast Discount Mapping</label>
    <nameField>
        <label>Discount Maping Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>OriPlast Discount Mappings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/OriPlast_Product__c.object
<CustomObject>
    <fields>
        <fullName>Base_Unit_of_Measure__c</fullName>
        <description>This field is used for entering a unit of measurement adopted for a base quantity</description>
        <inlineHelpText>It is used for entering Base unit of measure.</inlineHelpText>
        <label>Base Unit of Measure</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Category_Picklist__c</fullName>
        <description>This is a picklist field for choosing type of Category for the customers who search for products.</description>
        <inlineHelpText>This is a picklist field for choosing type of category.</inlineHelpText>
        <label>Category</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>P1</fullName>
                    <label>PVC Pipe ASTM-D-1785, PVC ASTM (Schdule)</label>
                </value>
                <value>
                    <fullName>P2</fullName>
                    <label>PVC Grey pipes as per IS : 4985,UPVC IS 4985</label>
                </value>
                <value>
                    <fullName>P3</fullName>
                    <label>CASING &amp; PVC Casing Pipes as per IS : 12818</label>
                </value>
                <value>
                    <fullName>P4</fullName>
                    <label>PVC SCREEN &amp; PVC Screen Pipes as per IS : 12818</label>
                </value>
                <value>
                    <fullName>P5</fullName>
                    <label>PVC GARDEN HOSE PIPE</label>
                </value>
                <value>
                    <fullName>P6</fullName>
                    <label>PVC SWR pipes &amp; fittings as per IS:13592</label>
                </value>
                <value>
                    <fullName>P7</fullName>
                    <label>PVC Column Pipe</label>
                </value>
                <value>
                    <fullName>P8</fullName>
                    <label>PVC Submersible</label>
                </value>
                <value>
                    <fullName>P9</fullName>
                    <label>CPVC Pipe</label>
                </value>
                <value>
                    <fullName>PF</fullName>
                    <label>PVC Fittings</label>
                </value>
                <value>
                    <fullName>H1</fullName>
                    <label>HDPE Pipe IS 4984 (Black)</label>
                </value>
                <value>
                    <fullName>H2</fullName>
                    <label>HDPE Pipe IS 14333 (Black)</label>
                </value>
                <value>
                    <fullName>H3</fullName>
                    <label>GI STANDERD &amp; PLB Duct Pipe</label>
                </value>
                <value>
                    <fullName>H4</fullName>
                    <label>HDPE IS 4427 (Blue/Black)</label>
                </value>
                <value>
                    <fullName>H5</fullName>
                    <label>HDPE 4984-2016</label>
                </value>
                <value>
                    <fullName>HF</fullName>
                    <label>HDPE Fittings</label>
                </value>
                <value>
                    <fullName>DF</fullName>
                    <label>Direct Action Hand Pump Fittings</label>
                </value>
                <value>
                    <fullName>M1</fullName>
                    <label>MDPE Pipe &amp; MDPE IS 14885</label>
                </value>
                <value>
                    <fullName>M2</fullName>
                    <label>MDPE pipe &amp; MDPE IS 4427</label>
                </value>
                <value>
                    <fullName>SL</fullName>
                    <label>Solvent Cement</label>
                </value>
                <value>
                    <fullName>NI</fullName>
                    <label>PVC SWR pipes &amp; fittings (non-standard)</label>
                </value>
                <value>
                    <fullName>DP</fullName>
                    <label>Direct Action Hand Pump Set</label>
                </value>
                <value>
                    <fullName>H6</fullName>
                    <label>PPR</label>
                </value>
                <value>
                    <fullName>H7</fullName>
                    <label>HDPE Copper Wire</label>
                </value>
                <value>
                    <fullName>M3</fullName>
                    <label>PE PIPE(MDPE)</label>
                </value>
                <value>
                    <fullName>MF</fullName>
                    <label>MDPE Fittings</label>
                </value>
                <value>
                    <fullName>OF</fullName>
                    <label>OPVC Fittings</label>
                </value>
                <value>
                    <fullName>OP</fullName>
                    <label>OPVC Pipe</label>
                </value>
                <value>
                    <fullName>WT</fullName>
                    <label>WATER TANK and FITTINGS</label>
                </value>
                <value>
                    <fullName>TW</fullName>
                    <isActive>false</isActive>
                    <label>ASTM-D 1785 Push type White, Solvent Ciment Type</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Item_Disc_Group__c</fullName>
        <description>Here the discounts are defined for specific items or item groups.</description>
        <inlineHelpText>It is used for entering Item Discount Group</inlineHelpText>
        <label>Item Disc. Group</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OriPlast_Product_Unique_Key__c</fullName>
        <caseSensitive>true</caseSensitive>
        <description>This is an External Id Field For Ori-Plast product.</description>
        <externalId>true</externalId>
        <label>Ori-Plast Product Unique Key</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Product_Category_Code_Picklist__c</fullName>
        <description>This picklist field is used for choosing code of a category of a product</description>
        <inlineHelpText>It is used for choosing Product Category Code.</inlineHelpText>
        <label>Product Category Code</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>PVC</fullName>
                    <default>true</default>
                    <label>PVC</label>
                </value>
                <value>
                    <fullName>HDPE</fullName>
                </value>
                <value>
                    <fullName>MDPE</fullName>
                </value>
                <value>
                    <fullName>Fabricated</fullName>
                </value>
                <value>
                    <fullName>Moulding</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Sub_Category_Picklist__c</fullName>
        <description>This is kind of picklist for choosing Sub Category of a product that is nested in another category.</description>
        <inlineHelpText>It is used for choosing Sub Category of a product.</inlineHelpText>
        <label>Sub Category</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Category_Picklist__c</controllingField>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>ASTM</fullName>
                </value>
                <value>
                    <fullName>CLASS1 (SDR11)</fullName>
                </value>
                <value>
                    <fullName>ISO 4427 Fittings</fullName>
                </value>
                <value>
                    <fullName>Male Thread</fullName>
                </value>
                <value>
                    <fullName>Pipe Grade PE 63</fullName>
                </value>
                <value>
                    <fullName>SDR 41</fullName>
                </value>
                <value>
                    <fullName>Single Socket</fullName>
                </value>
                <value>
                    <fullName>Pipe Grade PE 80</fullName>
                </value>
                <value>
                    <fullName>SDR 33</fullName>
                </value>
                <value>
                    <fullName>Bell End</fullName>
                </value>
                <value>
                    <fullName>CLASS2 (SDR 13.5)</fullName>
                </value>
                <value>
                    <fullName>Double Socket</fullName>
                </value>
                <value>
                    <fullName>IS 14333 Fittings</fullName>
                </value>
                <value>
                    <fullName>Male / Female Thread</fullName>
                </value>
                <value>
                    <fullName>UPVC</fullName>
                </value>
                <value>
                    <fullName>SDR 26</fullName>
                </value>
                <value>
                    <fullName>Pipe Grade PE 100</fullName>
                </value>
                <value>
                    <fullName>Plain End</fullName>
                </value>
                <value>
                    <fullName>Push Type</fullName>
                </value>
                <value>
                    <fullName>Sliding Socket</fullName>
                </value>
                <value>
                    <fullName>SWR</fullName>
                </value>
                <value>
                    <fullName>SDR 21</fullName>
                </value>
                <value>
                    <fullName>Cam Lock</fullName>
                </value>
                <value>
                    <fullName>CPVC</fullName>
                </value>
                <value>
                    <fullName>Flush Joint</fullName>
                </value>
                <value>
                    <fullName>SDR 17</fullName>
                </value>
                <value>
                    <fullName>LED &amp; TIN FREE</fullName>
                </value>
                <value>
                    <fullName>SDR 13.6</fullName>
                </value>
                <value>
                    <fullName>SDR 11</fullName>
                </value>
                <value>
                    <fullName>SDR 9</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Ori-Plast Product</label>
    <nameField>
        <label>Ori-PlastProduct Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Ori-Plast Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Product_Price__c.object
<CustomObject>
    <fields>
        <fullName>Items_Description__c</fullName>
        <description>This Field Store Product Name</description>
        <label>Items Description</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Oriplast_Product__c</fullName>
        <label>Oriplast Product</label>
        <referenceTo>OriPlast_Product__c</referenceTo>
        <relationshipLabel>Product Prices</relationshipLabel>
        <relationshipName>Product_Prices</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Product Price</label>
    <nameField>
        <displayFormat>PN-{000000}</displayFormat>
        <label>Product Price Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Product Prices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/PrintInvoicePageControllerTest.cls
@isTest
private class PrintInvoicePageControllerTest {
    @isTest
    static void testProcessInvoice() {
        // Create Account
        Account acc = new Account(Name = 'Test Account',
                                  Type= 'Distributor',
                                  Customer_Disc_Group__c = 'CDGOR',
                                  Phone = '23343434'
                                 );
        insert acc;
        
        // Create Ori_Plast_Order__c record
        Ori_Plast_Order__c order = new Ori_Plast_Order__c(
            Account__c = acc.Id
        );
        insert order;
        
        // Set the recordId parameter
        Test.setCurrentPageReference(new PageReference('/apex/PrintInvoicePageController'));
        ApexPages.currentPage().getParameters().put('id', order.Id);
        
        // Create Ori_Plast_Product__c record
        OriPlast_Product__c Oproduct= new OriPlast_Product__c(
            Name='90 mm 4kgf/sq cm UPVC Pipe Plain End 5 Mtr',
            Base_Unit_of_Measure__c = 'PCS',
            Category_Picklist__c = 'P2',
            Product_Category_Code_Picklist__c='PVC',
            Sub_Category_Picklist__c='Plain End',
            Item_Disc_Group__c='PVCPI-4985',
            OriPlast_Product_Unique_Key__c='FP201PN040GY00500090'
        );
        insert Oproduct;
        // Create Ori_Plast_Product Price record
        Product_Price__c ProPrice = new Product_Price__c(
            Items_Description__c= '90 mm 4kgf/sq cm UPVC Pipe Plain End 5 Mtr',
            Starting_Date__c = System.Today()-3,
            Unit_of_Measure_Code__c = 'MTR',
            Sales_Type__c = 'All Customers',
            Unit_Price__c = 100,
            Oriplast_Product__c = Oproduct.Id
        );
        insert ProPrice;
        // Create OriPlast_Discount_Mapping__c record
        OriPlast_Discount_Mapping__c DicMap = new OriPlast_Discount_Mapping__c(
            Name = 'PVCPI-4985',
            Cash_Discount__c = 4,
            Discount__c = 50,
            ItemDiscountCode_ExternalKey__c = 'CDGOR_PVCPI-4985'
        );
        insert DicMap;
        
        
        
        List< OriPlast_Product__c> OriProduct = [select id,Name,Item_Disc_Group__c,GST_Value__c from OriPlast_Product__c where OriPlast_Product_Unique_Key__c ='FP201PN040GY00500090' Limit 1];
        List<Product_Price__c> ProductPrice = [select Id,Unit_Price__c from Product_Price__c where Oriplast_Product__c =:OriProduct[0].Id ];
        String concatenatedValue = acc.Customer_Disc_Group__c + '_' + oriProduct[0].Item_Disc_Group__c;
        List <  OriPlast_Discount_Mapping__c> Discount = [select id,Discount__c,Cash_Discount__c from OriPlast_Discount_Mapping__c where ItemDiscountCode_ExternalKey__c =: concatenatedValue ];
        
        // Create Order_Line_Item__c records
        Decimal PriceAfterDiscount = (5*(ProductPrice[0].Unit_Price__c))-(((5*(ProductPrice[0].Unit_Price__c))*(Discount[0].Discount__c/100))+((5*(ProductPrice[0].Unit_Price__c))*(Discount[0].Cash_Discount__c/100)));
        Decimal TotalGst = PriceAfterDiscount*(OriProduct[0].GST_Value__c/100);
        Order_Line_Item__c lineItem1 = new Order_Line_Item__c(
            Ori_Plast_Order__c = order.Id,
            Quantity__c = 5,
            OriPlast_Product_Price__c=ProductPrice[0].Id,
            Ori_Plast_Product__c = OriProduct[0].Id,
            Trade_Discount_TD__c = (5*(ProductPrice[0].Unit_Price__c))*(Discount[0].Discount__c/100),
            Cash_Discount_CD__c	 = (5*(ProductPrice[0].Unit_Price__c))*(Discount[0].Cash_Discount__c/100),
            Price_After_Discount__c = PriceAfterDiscount,
            CGST__c = TotalGst/2,
            SGST__c = TotalGst/2,
            Final_Price__c = PriceAfterDiscount + TotalGst
        );
        
        // Create Ori_Plast_Product__c record
        OriPlast_Product__c Oproduct2= new OriPlast_Product__c(
            Name='90 mm 4kgf/sq cm UPVC Pipe Plain End 5 Mtr',
            Base_Unit_of_Measure__c = 'PCS',
            Category_Picklist__c = 'P2',
            Product_Category_Code_Picklist__c='PVC',
            Sub_Category_Picklist__c='Plain End',
            Item_Disc_Group__c='PVCPI-4985',
            OriPlast_Product_Unique_Key__c='FP201PN040GY00500091'
        );
        insert Oproduct2;
        
        
        // Create Ori_Plast_Product Price record
        Product_Price__c ProPrice2 = new Product_Price__c(
            Items_Description__c= '90 mm 4kgf/sq cm UPVC Pipe Plain End 5 Mtr',
            Starting_Date__c = System.Today()-3,
            Unit_of_Measure_Code__c = 'MTR',
            Sales_Type__c = 'All Customers',
            Unit_Price__c = 10000.25,
            Oriplast_Product__c = Oproduct2.Id
        );
        insert ProPrice2;
        
        List< OriPlast_Product__c> OriProduct2 = [select id,Name,Item_Disc_Group__c,GST_Value__c from OriPlast_Product__c where OriPlast_Product_Unique_Key__c ='FP201PN040GY00500091' Limit 1];
        List<Product_Price__c> ProductPrice2 = [select Id,Unit_Price__c from Product_Price__c where Oriplast_Product__c =:OriProduct2[0].Id ];
        String concatenatedValue2 = acc.Customer_Disc_Group__c + '_' + oriProduct2[0].Item_Disc_Group__c;
        List <  OriPlast_Discount_Mapping__c> Discount2 = [select id,Discount__c,Cash_Discount__c from OriPlast_Discount_Mapping__c where ItemDiscountCode_ExternalKey__c =: concatenatedValue2 ];
        
        
        Decimal PriceAfterDiscount2 = (10*(ProductPrice2[0].Unit_Price__c))-(((10*(ProductPrice2[0].Unit_Price__c))*(Discount2[0].Discount__c/100))+((10*(ProductPrice2[0].Unit_Price__c))*(Discount2[0].Cash_Discount__c/100)));
        Decimal TotalGst2 = PriceAfterDiscount*(OriProduct2[0].GST_Value__c/100);
        
        Order_Line_Item__c lineItem2 = new Order_Line_Item__c(
            Ori_Plast_Order__c = order.Id,
            Quantity__c = 10,
            OriPlast_Product_Price__c=ProductPrice2[0].Id,
            Ori_Plast_Product__c = OriProduct2[0].Id,
            Trade_Discount_TD__c = (10*(ProductPrice2[0].Unit_Price__c))*(Discount2[0].Discount__c/100),
            Cash_Discount_CD__c	 = (10*(ProductPrice2[0].Unit_Price__c))*(Discount2[0].Cash_Discount__c/100),
            Price_After_Discount__c = PriceAfterDiscount2,
            CGST__c = TotalGst2/2,
            SGST__c = TotalGst2/2,
            Final_Price__c = PriceAfterDiscount2 + TotalGst2
        );
        
        // Create Ori_Plast_Product__c record
        OriPlast_Product__c Oproduct3 = new OriPlast_Product__c(
            Name='Another Product',
            Base_Unit_of_Measure__c = 'PCS',
            Category_Picklist__c = 'P2',
            Product_Category_Code_Picklist__c='PVC',
            Sub_Category_Picklist__c='Plain End',
            Item_Disc_Group__c='PVCPI-49856',
            OriPlast_Product_Unique_Key__c='FP201PN040GY00500092'
        );
        insert Oproduct3;
        
        // Create Ori_Plast_Product Price record
        Product_Price__c ProPrice3 = new Product_Price__c(
            Items_Description__c= 'Another Product Description',
            Starting_Date__c = System.Today()-3,
            Unit_of_Measure_Code__c = 'MTR',
            Sales_Type__c = 'All Customers',
            Unit_Price__c = 12344444.55,
            Oriplast_Product__c = Oproduct3.Id
        );
        insert ProPrice3;
         // Create OriPlast_Discount_Mapping__c record
        OriPlast_Discount_Mapping__c DicMap2 = new OriPlast_Discount_Mapping__c(
            Name = 'PVCPI-49856',
            Cash_Discount__c = 4,
            Discount__c = 5,
            ItemDiscountCode_ExternalKey__c = 'CDGOR_PVCPI-49856'
        );
        insert DicMap2;
        
        List< OriPlast_Product__c> OriProduct3 = [select id,Name,Item_Disc_Group__c,GST_Value__c from OriPlast_Product__c where OriPlast_Product_Unique_Key__c ='FP201PN040GY00500092' Limit 1];
        List<Product_Price__c> ProductPrice3 = [select Id,Unit_Price__c from Product_Price__c where Oriplast_Product__c =:OriProduct3[0].Id ];
        String concatenatedValue3 = acc.Customer_Disc_Group__c + '_' + oriProduct3[0].Item_Disc_Group__c;
        List <  OriPlast_Discount_Mapping__c> Discount3 = [select id,Discount__c,Cash_Discount__c from OriPlast_Discount_Mapping__c where ItemDiscountCode_ExternalKey__c =: concatenatedValue3 ];
        
        Decimal PriceAfterDiscount3 = (10*(ProductPrice3[0].Unit_Price__c))-(((10*(ProductPrice3[0].Unit_Price__c))*(Discount3[0].Discount__c/100))+((10*(ProductPrice3[0].Unit_Price__c))*(Discount3[0].Cash_Discount__c/100)));
        Decimal TotalGst3 = PriceAfterDiscount*(OriProduct3[0].GST_Value__c/100);
        
        Order_Line_Item__c lineItem3 = new Order_Line_Item__c(
            Ori_Plast_Order__c = order.Id,
            Quantity__c = 10,
            OriPlast_Product_Price__c=ProductPrice3[0].Id,
            Ori_Plast_Product__c = OriProduct3[0].Id,
            Trade_Discount_TD__c = (10*(ProductPrice3[0].Unit_Price__c))*(Discount3[0].Discount__c/100),
            Cash_Discount_CD__c	 = (10*(ProductPrice2[0].Unit_Price__c))*(Discount3[0].Cash_Discount__c/100),
            Price_After_Discount__c = PriceAfterDiscount3,
            CGST__c = TotalGst3/2,
            SGST__c = TotalGst3/2,
            Final_Price__c = PriceAfterDiscount3 + TotalGst3
        );
         // Create Ori_Plast_Product__c record
        OriPlast_Product__c Oproduct4 = new OriPlast_Product__c(
            Name='Another Product',
            Base_Unit_of_Measure__c = 'PCS',
            Category_Picklist__c = 'P2',
            Product_Category_Code_Picklist__c='PVC',
            Sub_Category_Picklist__c='Plain End',
            Item_Disc_Group__c='PVCPI-49857',
            OriPlast_Product_Unique_Key__c='FP201PN040GY00500093'
        );
        insert Oproduct4;
        // Create Ori_Plast_Product Price record
        Product_Price__c ProPrice4 = new Product_Price__c(
            Items_Description__c= 'Another Product Description',
            Starting_Date__c = System.Today()-3,
            Unit_of_Measure_Code__c = 'MTR',
            Sales_Type__c = 'All Customers',
            Unit_Price__c = 123,
            Oriplast_Product__c = Oproduct4.Id
        );
        insert ProPrice4;
        // Create OriPlast_Discount_Mapping__c record
        OriPlast_Discount_Mapping__c DicMap3 = new OriPlast_Discount_Mapping__c(
            Name = 'PVCPI-49857',
            Cash_Discount__c = 4,
            Discount__c = 10,
            ItemDiscountCode_ExternalKey__c = 'CDGOR_PVCPI-49857'
        );
        insert DicMap3;
        List< OriPlast_Product__c> OriProduct4 = [select id,Name,Item_Disc_Group__c,GST_Value__c from OriPlast_Product__c where OriPlast_Product_Unique_Key__c ='FP201PN040GY00500093' Limit 1];
        List<Product_Price__c> ProductPrice4 = [select Id,Unit_Price__c from Product_Price__c where Oriplast_Product__c =:OriProduct4[0].Id ];
        String concatenatedValue4 = acc.Customer_Disc_Group__c + '_' + oriProduct4[0].Item_Disc_Group__c;
        List <  OriPlast_Discount_Mapping__c> Discount4 = [select id,Discount__c,Cash_Discount__c from OriPlast_Discount_Mapping__c where ItemDiscountCode_ExternalKey__c =: concatenatedValue4 ];
         Decimal PriceAfterDiscount4 = (10*(ProductPrice4[0].Unit_Price__c))-(((10*(ProductPrice4[0].Unit_Price__c))*(Discount4[0].Discount__c/100))+((10*(ProductPrice4[0].Unit_Price__c))*(Discount4[0].Cash_Discount__c/100)));
        Decimal TotalGst4 = PriceAfterDiscount*(OriProduct4[0].GST_Value__c/100);
        
        Order_Line_Item__c lineItem4 = new Order_Line_Item__c(
            Ori_Plast_Order__c = order.Id,
            Quantity__c = 10,
            OriPlast_Product_Price__c=ProductPrice4[0].Id,
            Ori_Plast_Product__c = OriProduct4[0].Id,
            Trade_Discount_TD__c = (10*(ProductPrice4[0].Unit_Price__c))*(Discount4[0].Discount__c/100),
            Cash_Discount_CD__c	 = (10*(ProductPrice4[0].Unit_Price__c))*(Discount4[0].Cash_Discount__c/100),
            Price_After_Discount__c = PriceAfterDiscount4,
            CGST__c = TotalGst4/2,
            SGST__c = TotalGst4/2,
            Final_Price__c = PriceAfterDiscount4 + TotalGst4
        );

        insert new List<Order_Line_Item__c>{lineItem1, lineItem2,lineItem3,lineItem4};
            
            Test.startTest();
        // Call the method
        PrintInvoicePageController controller = new PrintInvoicePageController();
        controller.processInvoice();
        // Assert the results if necessary
        Test.stopTest();
    }
    
}