objects/Account.object
<CustomObject>
    <fields>
        <fullName>Associated_User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field is used to get related User</description>
        <inlineHelpText>This is for an associated user field</inlineHelpText>
        <label>Associated User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Order_Line_Item__c.object
<CustomObject>
    <fields>
        <fullName>Ori_Plast_Order__c</fullName>
        <description>Lookup with Ori-plast Order</description>
        <label>Ori-Plast Order</label>
        <referenceTo>Ori_Plast_Order__c</referenceTo>
        <relationshipLabel>Order-Line-Items</relationshipLabel>
        <relationshipName>Order_Line_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Ori_Plast_Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup with Ori-plast Product</description>
        <label>Ori-Plast Product</label>
        <referenceTo>OriPlast_Product__c</referenceTo>
        <relationshipLabel>Order-Line-Items</relationshipLabel>
        <relationshipName>Order_Line_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Unit_of_Measure__c</fullName>
        <label>Unit of Measure</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Order-Line-Item</label>
    <nameField>
        <displayFormat>OLN-{000000}</displayFormat>
        <label>Order-Line-Item No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Order-Line-Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Ori_Plast_Order__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <description>Ori-plast product Supplier</description>
        <inlineHelpText>The distributor account that generated the sales order.</inlineHelpText>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Ori-Plast Orders</relationshipLabel>
        <relationshipName>Ori_Plast_Orders</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Order_Status__c</fullName>
        <description>This field state different stage of orders</description>
        <inlineHelpText>Order Status indicates various order stages.</inlineHelpText>
        <label>Order Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                    <color>#FF9900</color>
                    <default>true</default>
                    <label>Draft</label>
                </value>
                <value>
                    <fullName>Submitted</fullName>
                    <color>#33FFFF</color>
                    <label>Submitted</label>
                </value>
                <value>
                    <fullName>Received by Navision</fullName>
                    <color>#66FF99</color>
                    <label>Received by Business Central</label>
                </value>
                <value>
                    <fullName>Partially Delivered</fullName>
                    <color>#66CCCC</color>
                    <label>Partially Delivered</label>
                </value>
                <value>
                    <fullName>Delivered</fullName>
                    <color>#33CC00</color>
                    <label>Delivered</label>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                    <isActive>false</isActive>
                    <label>Cancelled</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Ori-Plast Order</label>
    <nameField>
        <displayFormat>ON-26-27-{000000}</displayFormat>
        <label>Ori-Plast Order No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Ori-Plast Orders</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/OriPlast_Product__c.object
<CustomObject>
    <fields>
        <fullName>Base_Unit_of_Measure__c</fullName>
        <description>This field is used for entering a unit of measurement adopted for a base quantity</description>
        <inlineHelpText>It is used for entering Base unit of measure.</inlineHelpText>
        <label>Base Unit of Measure</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Category_Picklist__c</fullName>
        <description>This is a picklist field for choosing type of Category for the customers who search for products.</description>
        <inlineHelpText>This is a picklist field for choosing type of category.</inlineHelpText>
        <label>Category</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>P1</fullName>
                    <label>PVC Pipe ASTM-D-1785, PVC ASTM (Schdule)</label>
                </value>
                <value>
                    <fullName>P2</fullName>
                    <label>PVC Grey pipes as per IS : 4985,UPVC IS 4985</label>
                </value>
                <value>
                    <fullName>P3</fullName>
                    <label>CASING &amp; PVC Casing Pipes as per IS : 12818</label>
                </value>
                <value>
                    <fullName>P4</fullName>
                    <label>PVC SCREEN &amp; PVC Screen Pipes as per IS : 12818</label>
                </value>
                <value>
                    <fullName>P5</fullName>
                    <label>PVC GARDEN HOSE PIPE</label>
                </value>
                <value>
                    <fullName>P6</fullName>
                    <label>PVC SWR pipes &amp; fittings as per IS:13592</label>
                </value>
                <value>
                    <fullName>P7</fullName>
                    <label>PVC Column Pipe</label>
                </value>
                <value>
                    <fullName>P8</fullName>
                    <label>PVC Submersible</label>
                </value>
                <value>
                    <fullName>P9</fullName>
                    <label>CPVC Pipe</label>
                </value>
                <value>
                    <fullName>PF</fullName>
                    <label>PVC Fittings</label>
                </value>
                <value>
                    <fullName>H1</fullName>
                    <label>HDPE Pipe IS 4984 (Black)</label>
                </value>
                <value>
                    <fullName>H2</fullName>
                    <label>HDPE Pipe IS 14333 (Black)</label>
                </value>
                <value>
                    <fullName>H3</fullName>
                    <label>GI STANDERD &amp; PLB Duct Pipe</label>
                </value>
                <value>
                    <fullName>H4</fullName>
                    <label>HDPE IS 4427 (Blue/Black)</label>
                </value>
                <value>
                    <fullName>H5</fullName>
                    <label>HDPE 4984-2016</label>
                </value>
                <value>
                    <fullName>HF</fullName>
                    <label>HDPE Fittings</label>
                </value>
                <value>
                    <fullName>DF</fullName>
                    <label>Direct Action Hand Pump Fittings</label>
                </value>
                <value>
                    <fullName>M1</fullName>
                    <label>MDPE Pipe &amp; MDPE IS 14885</label>
                </value>
                <value>
                    <fullName>M2</fullName>
                    <label>MDPE pipe &amp; MDPE IS 4427</label>
                </value>
                <value>
                    <fullName>SL</fullName>
                    <label>Solvent Cement</label>
                </value>
                <value>
                    <fullName>NI</fullName>
                    <label>PVC SWR pipes &amp; fittings (non-standard)</label>
                </value>
                <value>
                    <fullName>DP</fullName>
                    <label>Direct Action Hand Pump Set</label>
                </value>
                <value>
                    <fullName>H6</fullName>
                    <label>PPR</label>
                </value>
                <value>
                    <fullName>H7</fullName>
                    <label>HDPE Copper Wire</label>
                </value>
                <value>
                    <fullName>M3</fullName>
                    <label>PE PIPE(MDPE)</label>
                </value>
                <value>
                    <fullName>MF</fullName>
                    <label>MDPE Fittings</label>
                </value>
                <value>
                    <fullName>OF</fullName>
                    <label>OPVC Fittings</label>
                </value>
                <value>
                    <fullName>OP</fullName>
                    <label>OPVC Pipe</label>
                </value>
                <value>
                    <fullName>WT</fullName>
                    <label>WATER TANK and FITTINGS</label>
                </value>
                <value>
                    <fullName>TW</fullName>
                    <isActive>false</isActive>
                    <label>ASTM-D 1785 Push type White, Solvent Ciment Type</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>GST_Value__c</fullName>
        <description>This Field is used to calculate GST on flow</description>
        <formula>IF( GST_Group_Code__c  = &quot;G18.00&quot;, 18,  IF(GST_Group_Code__c  = &quot;G05.00&quot;, 5, 00) )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>GST Value</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Identifire_Picklist__c</fullName>
        <description>This is an information element  that are used to establish the unique identity.</description>
        <inlineHelpText>This is for entering unique identity.</inlineHelpText>
        <label>Identifier</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Category_Picklist__c</controllingField>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>PN100</fullName>
                    <label>10kgf/sq</label>
                </value>
                <value>
                    <fullName>PN125</fullName>
                    <label>12.5kgf/sq</label>
                </value>
                <value>
                    <fullName>PN025</fullName>
                    <label>2.5kgf/sq</label>
                </value>
                <value>
                    <fullName>45DY0</fullName>
                </value>
                <value>
                    <fullName>PN040</fullName>
                    <label>4kgf/sq</label>
                </value>
                <value>
                    <fullName>PN060</fullName>
                    <label>6kgf/sq</label>
                </value>
                <value>
                    <fullName>PN06E</fullName>
                    <label>6kgf/sq Elastomeric Pipe</label>
                </value>
                <value>
                    <fullName>PN080</fullName>
                    <label>8kgf/sq</label>
                </value>
                <value>
                    <fullName>AD000</fullName>
                    <label>Adaptor</label>
                </value>
                <value>
                    <fullName>ADHVY</fullName>
                    <label>Adhesive Heavy</label>
                </value>
                <value>
                    <fullName>ADCM0</fullName>
                    <label>Adopter CM</label>
                </value>
                <value>
                    <fullName>AIRCP</fullName>
                </value>
                <value>
                    <fullName>AL576</fullName>
                </value>
                <value>
                    <fullName>ASTE0</fullName>
                </value>
                <value>
                    <fullName>ASTEE</fullName>
                </value>
                <value>
                    <fullName>BV000</fullName>
                    <label>Ball Valve</label>
                </value>
                <value>
                    <fullName>BVUNE</fullName>
                    <label>Ball Valve (Union Ended)</label>
                </value>
                <value>
                    <fullName>BVCSC</fullName>
                    <label>Ball Valve CPVC Concealed Stop Cock</label>
                </value>
                <value>
                    <fullName>BVSSH</fullName>
                    <label>Ball Valve SS Handle</label>
                </value>
                <value>
                    <fullName>BCWSH</fullName>
                </value>
                <value>
                    <fullName>BE225</fullName>
                </value>
                <value>
                    <fullName>BE450</fullName>
                </value>
                <value>
                    <fullName>BE000</fullName>
                    <label>Bend</label>
                </value>
                <value>
                    <fullName>BEND0</fullName>
                </value>
                <value>
                    <fullName>BE105</fullName>
                    <label>Bend 105 Deg</label>
                </value>
                <value>
                    <fullName>BE011</fullName>
                    <label>Bend 11 1/4 Deg</label>
                </value>
                <value>
                    <fullName>BE120</fullName>
                    <label>Bend 120 Deg</label>
                </value>
                <value>
                    <fullName>BE135</fullName>
                    <label>Bend 135 Deg</label>
                </value>
                <value>
                    <fullName>BE148</fullName>
                    <label>Bend 148 Deg</label>
                </value>
                <value>
                    <fullName>BE150</fullName>
                    <label>Bend 150 Deg</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Item_Disc_Group__c</fullName>
        <description>Here the discounts are defined for specific items or item groups.</description>
        <inlineHelpText>It is used for entering Item Discount Group</inlineHelpText>
        <label>Item Disc. Group</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Ori-Plast Product</label>
    <nameField>
        <label>Ori-PlastProduct Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Ori-Plast Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/OutstandingOrderValueTest.cls
@IsTest
private class OutstandingOrderValueTest {

    /* =========================
       TEST SETUP
       ========================= */
    @testSetup
static void setupData() {

    User u = [SELECT Id FROM User WHERE IsActive = true LIMIT 1];

    Account acc = new Account(
        Name = 'Test Distributor',
        Type = 'Distributor',
        Associated_User__c = u.Id
    );
    insert acc;

    OriPlast_Product__c prod = new OriPlast_Product__c(
        Name = 'Test Product',
        Category_Picklist__c = 'P2',
        Identifire_Picklist__c = 'PN100',
        Base_Unit_of_Measure__c = 'Nos',
        //GST_Value__c = 18,
        Item_Disc_Group__c = 'DISC01'
    );
    insert prod;

    // 🔴 INSERT ORDER FIRST
    Ori_Plast_Order__c ord = new Ori_Plast_Order__c(
        Account__c = acc.Id,
        Order_Status__c = 'Draft'
    );
    insert ord;

    // 🔴 THEN INSERT LINE ITEM WITH ORDER ID
    Order_Line_Item__c oli = new Order_Line_Item__c(
        Ori_Plast_Order__c = ord.Id,       // ✅ REQUIRED
        Ori_Plast_Product__c = prod.Id,
        Quantity__c = 5,
        Final_Price__c = 500,
        Price_After_Discount__c = 450,
        //OriPlast_Product_Unit_Price__c = 100,
        CGST__c = 45,
        SGST__c = 45,
        Trade_Discount_TD__c = 10,
        Cash_Discount_CD__c = 5
        //Unit_of_Measure__c = 'Nos',
        //Ori_Plast_Product_Name__c = prod.Name
    );
    insert oli;
}
    /* =========================
       FETCH OUTSTANDING ORDER VALUE
       ========================= */
    @IsTest
    static void testgetTotalOutstandingValue() {
        
        Test.startTest();
        Decimal value = OutstandingOrderValue.getTotalOutstandingValue();
        Test.stopTest();

    }
    
    @IsTest
    static void testgetNumberTOWordConvertion1() {
        
        Test.startTest();
        String value = OutstandingOrderValue.getNumberTOWordConvertion(111111.20);
        Test.stopTest();
    }
    @IsTest
    static void testgetNumberTOWordConvertion2() {
        
        Test.startTest();
        String value = OutstandingOrderValue.getNumberTOWordConvertion(1111.20);
        Test.stopTest();
    }
    
    @IsTest
    static void testgetNumberTOWordConvertion3() {
        
        Test.startTest();
        String value = OutstandingOrderValue.getNumberTOWordConvertion(111);
        Test.stopTest();
    }
    
    @IsTest
    static void testgetNumberTOWordConvertion4() {
        
        Test.startTest();
        String value = OutstandingOrderValue.getNumberTOWordConvertion(111111111);
        Test.stopTest();
    }
}