objects/Account.object
<CustomObject>
    <fields>
        <fullName>Account_External_Key__c</fullName>
        <description>This Field used as a external id for data loading</description>
        <externalId>true</externalId>
        <label>Account External Key</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>GST_Registration_No__c</fullName>
        <description>Here will be entered a combination of code of GST Registration No</description>
        <inlineHelpText>it is for entering GST Registration No</inlineHelpText>
        <label>GST Registration No.</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>GST_Registration_Type__c</fullName>
        <description>Here will be entered what is the type of GST Registration?</description>
        <inlineHelpText>It is for entering GST Registration Type</inlineHelpText>
        <label>GST Registration Type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>P_A_N_No__c</fullName>
        <description>This field will be used for entering a unique 10 digit alphanumeric number.</description>
        <inlineHelpText>It is used for entering PAN no.</inlineHelpText>
        <label>P.A.N. No.</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Order_Line_Item__c.object
<CustomObject>
    <fields>
        <fullName>CGST__c</fullName>
        <description>This Field store CGST Price (Price After Discount * CGST%)</description>
        <label>CGST</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Cash_Discount_CD__c</fullName>
        <description>This Field store Cash Discount ((Quantity*Unit Price)*Cash Discount %</description>
        <label>Cash Discount(CD)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Cash_Discount_Percentage__c</fullName>
        <label>Cash Discount Percentage</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>ERP_Quantity__c</fullName>
        <formula>IF( CONTAINS(Unit_of_Measure__c, &apos;MTR&apos;) ,(Quantity__c * VALUE(Ori_Plast_Product__r.Length_In_Meter__c)), Quantity__c)</formula>
        <label>ERP Quantity</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>IGST__c</fullName>
        <description>This Field store IGST price (Price After Discount * IGST%)</description>
        <label>IGST</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>OriPlast_Product_Unit_Price__c</fullName>
        <description>This field fetch Unit Price from related product</description>
        <formula>OriPlast_Product_Price__r.Unit_Price__c</formula>
        <label>OriPlast Product Unit Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Ori_Plast_Order__c</fullName>
        <description>Lookup with Ori-plast Order</description>
        <label>Ori-Plast Order</label>
        <referenceTo>Ori_Plast_Order__c</referenceTo>
        <relationshipLabel>Order-Line-Items</relationshipLabel>
        <relationshipName>Order_Line_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Ori_Plast_Product_Name__c</fullName>
        <description>This Field is used to show Ori-Plast Product name in place order LWC</description>
        <formula>Ori_Plast_Product__r.Name</formula>
        <label>Ori-Plast Product Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Price_After_Discount__c</fullName>
        <description>This Field store After Discount Price ((Quantity*Unit Price)-Trade Discount - Cash Discount)</description>
        <label>Price After Discount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Quantity__c</fullName>
        <description>This is for Product quantity</description>
        <label>Quantity</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>SGST__c</fullName>
        <description>This Field store SGST price (Price After Discount * SGST%)</description>
        <label>SGST</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Total_Discount__c</fullName>
        <description>This Field store Total Discount (Trade Discount + Cash Discount)</description>
        <formula>Cash_Discount_CD__c  +  Trade_Discount_TD__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Total Discount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Total_Price__c</fullName>
        <description>This Field store Total Price (Quantity*Unit Price)</description>
        <formula>OriPlast_Product_Price__r.Unit_Price__c *  ERP_Quantity__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Total Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Trade_Discount_TD__c</fullName>
        <description>This Field store Trade Discount ((Quantity*Unit Price)*Trade Discount %)</description>
        <label>Trade Discount(TD)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Trade_Discount__c</fullName>
        <description>This Field store Trade Discount for A Product from Discount Mapping Obj. by flow</description>
        <label>Trade Discount</label>
        <precision>5</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Unit_of_Measure__c</fullName>
        <label>Unit of Measure</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Order-Line-Item</label>
    <nameField>
        <displayFormat>OLN-{000000}</displayFormat>
        <label>Order-Line-Item No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Order-Line-Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Ori_Plast_Order__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <description>Ori-plast product Supplier</description>
        <inlineHelpText>The distributor account that generated the sales order.</inlineHelpText>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Ori-Plast Orders</relationshipLabel>
        <relationshipName>Ori_Plast_Orders</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Final_Order_Value__c</fullName>
        <description>This field store Final Price(Price after discount+cgst+sgst)</description>
        <inlineHelpText>Calculated price of all submitted line items.</inlineHelpText>
        <label>Total Order Value</label>
        <summarizedField>Order_Line_Item__c.Final_Price__c</summarizedField>
        <summaryForeignKey>Order_Line_Item__c.Ori_Plast_Order__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Order_Status__c</fullName>
        <description>This field state different stage of orders</description>
        <inlineHelpText>Order Status indicates various order stages.</inlineHelpText>
        <label>Order Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                    <color>#FF9900</color>
                    <default>true</default>
                    <label>Draft</label>
                </value>
                <value>
                    <fullName>Submitted</fullName>
                    <color>#33FFFF</color>
                    <label>Submitted</label>
                </value>
                <value>
                    <fullName>Received by Navision</fullName>
                    <color>#66FF99</color>
                    <label>Received by Business Central</label>
                </value>
                <value>
                    <fullName>Partially Delivered</fullName>
                    <color>#66CCCC</color>
                    <label>Partially Delivered</label>
                </value>
                <value>
                    <fullName>Delivered</fullName>
                    <color>#33CC00</color>
                    <label>Delivered</label>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                    <isActive>false</isActive>
                    <label>Cancelled</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Total_CGST__c</fullName>
        <description>This field store total CGST from its Child Object(Order Line Items)</description>
        <inlineHelpText>Total Central GST</inlineHelpText>
        <label>Total Pending CGST</label>
        <summarizedField>Order_Line_Item__c.CGST__c</summarizedField>
        <summaryFilterItems>
            <field>Order_Line_Item__c.Status__c</field>
            <operation>notEqual</operation>
            <value>Delivered, Cancelled</value>
        </summaryFilterItems>
        <summaryForeignKey>Order_Line_Item__c.Ori_Plast_Order__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Total_Cash_Discount__c</fullName>
        <description>This field store Total Cash discount from its child object(Oder Line Items)</description>
        <label>Total Cash Discount</label>
        <summarizedField>Order_Line_Item__c.Cash_Discount_CD__c</summarizedField>
        <summaryFilterItems>
            <field>Order_Line_Item__c.Status__c</field>
            <operation>notEqual</operation>
            <value>Delivered, Cancelled</value>
        </summaryFilterItems>
        <summaryForeignKey>Order_Line_Item__c.Ori_Plast_Order__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Total_Discount__c</fullName>
        <description>This field store total Discount (Trade Discount+Cash Discount)  from its Child Object(Order Line Items)</description>
        <label>Total Discount</label>
        <summarizedField>Order_Line_Item__c.Total_Discount__c</summarizedField>
        <summaryFilterItems>
            <field>Order_Line_Item__c.Status__c</field>
            <operation>notEqual</operation>
            <value>Delivered, Cancelled</value>
        </summaryFilterItems>
        <summaryForeignKey>Order_Line_Item__c.Ori_Plast_Order__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Total_Order_Quantity__c</fullName>
        <description>This field store total Quantity from its Child Object(Order Line Items)</description>
        <label>Total Order Quantity</label>
        <summarizedField>Order_Line_Item__c.Quantity__c</summarizedField>
        <summaryForeignKey>Order_Line_Item__c.Ori_Plast_Order__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Total_Price_After_Discount__c</fullName>
        <description>This field store Price After Discount (Total Amount -(Trade discount + Cash Discount))  from its Child Object(Order Line Items)</description>
        <inlineHelpText>Calculated Price after applying all the discounts.</inlineHelpText>
        <label>Total Price After Discount</label>
        <summarizedField>Order_Line_Item__c.Price_After_Discount__c</summarizedField>
        <summaryFilterItems>
            <field>Order_Line_Item__c.Status__c</field>
            <operation>notEqual</operation>
            <value>Delivered, Cancelled</value>
        </summaryFilterItems>
        <summaryForeignKey>Order_Line_Item__c.Ori_Plast_Order__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Total_SGST__c</fullName>
        <description>This field store total SGST  from its Child Object(Order Line Items)</description>
        <inlineHelpText>Total State GST</inlineHelpText>
        <label>Total Pending SGST</label>
        <summarizedField>Order_Line_Item__c.SGST__c</summarizedField>
        <summaryFilterItems>
            <field>Order_Line_Item__c.Status__c</field>
            <operation>notEqual</operation>
            <value>Delivered, Cancelled</value>
        </summaryFilterItems>
        <summaryForeignKey>Order_Line_Item__c.Ori_Plast_Order__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Total_Trade_Discount__c</fullName>
        <description>This field store total Trade Discount   from its Child Object(Order Line Items)</description>
        <label>Total Trade Discount</label>
        <summarizedField>Order_Line_Item__c.Trade_Discount_TD__c</summarizedField>
        <summaryFilterItems>
            <field>Order_Line_Item__c.Status__c</field>
            <operation>notEqual</operation>
            <value>Delivered, Cancelled</value>
        </summaryFilterItems>
        <summaryForeignKey>Order_Line_Item__c.Ori_Plast_Order__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <label>Ori-Plast Order</label>
    <nameField>
        <displayFormat>ON-26-27-{000000}</displayFormat>
        <label>Ori-Plast Order No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Ori-Plast Orders</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/OriPlastProformaInvoiceAddressManagement__mdt.object
<CustomObject>
    <fields>
        <fullName>Address__c</fullName>
        <label>Address</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>OriPlastProformaInvoiceAddressManagement</label>
    <pluralLabel>OriPlastProformaInvoiceAddressManagement</pluralLabel>
</CustomObject>

classes/PrintInvoicePageController.cls
/*@company-- DataColada
@Date-- 23/03/2024
@Author-- Reetabrata Mishra
@Description--This class used in in VF page to map the field value
@Last Modified By-- Reetabrata Mishra
@Last Modified Date--26/03/2024 */


public class PrintInvoicePageController {
    public Ori_Plast_Order__c orders {get;set;}
    public Account acc {get;set;}
    public List<Order_Line_Item__c> lineItems {get;set;}
    public Decimal totalProductPrice { get; set; }
    public String finalOrderValueInWords { get; set; } // String to hold final order value in words
    public string orderDate { get; set; }
    public String proformaInvoiceAddress { get; set; }

    
    public  PageReference processInvoice() {
        string recordId= ApexPages.currentPage().getParameters().get('id');
        if (recordId != null) {
            
            // Perform the first query to retrieve Ori_Plast_Order__c records
            orders = [SELECT Id, Name, Total_CGST__c,
                      Total_Discount__c ,Total_Order_Quantity__c ,
                      Total_SGST__c ,Account__c ,CreatedDate, Final_Order_Value__c, 
                      Total_Cash_Discount__c,Total_Trade_Discount__c,
                       Total_Price_After_Discount__c,Order_Status__c FROM Ori_Plast_Order__c WHERE Id = :recordId LIMIT 1];
            System.debug('Oriplast oder Query result: ' + orders);
            
                    orderDate = orders.CreatedDate.format().remove('00:00:00 GMT');
               

            
            acc = [select Name,GST_Registration_No__c ,GST_Registration_Type__c , P_A_N_No__c, 
                  BillingStreet,BillingCity,BillingPostalCode,BillingState,BillingCountry,Account_External_Key__c
                   from Account where id =:orders.Account__c];
            
            System.debug('Oriplast Account Query result: ' + acc);
            if (acc != null && acc.Account_External_Key__c != null) {
            List<OriPlastProformaInvoiceAddressManagement__mdt> metadataRecords = [
                SELECT MasterLabel, Address__c  
                FROM OriPlastProformaInvoiceAddressManagement__mdt 
                WHERE MasterLabel = :acc.Account_External_Key__c LIMIT 1
            ];

            if (!metadataRecords.isEmpty()) {
                proformaInvoiceAddress = metadataRecords[0].Address__c ;
            } else {
                proformaInvoiceAddress = null;
            }
        } else {
            proformaInvoiceAddress = null;
        }
            // Process the query results
            if (orders!=null) {
                Ori_Plast_Order__c order = orders;
                System.debug('Oriplast oder Query result: ' + order);
                
                // Perform the second query to retrieve related Order_Line_Item__c records
                lineItems = [SELECT Id, Name,Cash_Discount_CD__c ,CGST__c ,IGST__c ,
                             Ori_Plast_Product_Name__c ,OriPlast_Product_Unit_Price__c ,Cash_Discount_Percentage__c ,
                             Price_After_Discount__c ,SGST__c ,Unit_of_Measure__c ,ERP_Quantity__c ,Total_Discount__c ,Total_Price__c ,
                             Trade_Discount_TD__c ,Quantity__c,Ori_Plast_Product__r.HSN_SAC_Code__c,  
                             Ori_Plast_Product__r.GST_Value__c,Trade_Discount__c,
                              CGST_Percentage__c ,SGST_Percentage__c FROM Order_Line_Item__c WHERE Ori_Plast_Order__c = :order.Id];
                
                System.debug('Order_Line_Item__c Query result: ' + lineItems);
                //Calculating Total Product Price
                totalProductPrice = 0;
                for (Order_Line_Item__c item : lineItems) {
                    totalProductPrice += item.Total_Price__c;
                }
                System.debug('total Product Price: ' + totalProductPrice);
                
                finalOrderValueInWords= getNumberTOWordConvertion(orders.Final_Order_Value__c);
                
            } else {
                System.debug('No Ori_Plast_Order__c records found for the provided ID.');
            }
        } else {
            System.debug('No record ID available.');
        }
        return null;
    }
    
    public String getNumberTOWordConvertion(Decimal num) {
        
        Decimal junkVal = num;
        Decimal junkValPaisa = junkVal - Math.floor(junkVal);
        junkVal = Math.floor(junkVal);
        
        String obStr = junkVal.toPlainString();
        String[] numReversed = obStr.split('');
        String[] actnumber = reverse(numReversed);
        String firstHalf = convertInWords(numReversed, actnumber);
        
        Integer tmp = Math.round(junkValPaisa * 100);
        junkValPaisa = (Decimal)tmp / 100; System.debug('jj :' + junkValPaisa);
        String paisaStr = junkValPaisa.toPlainString();
        String secondHalf;
        if (paisaStr == '0') {
            secondHalf = '';
        } else if (paisaStr.length() != 4) {
            paisaStr = paisaStr + '0';
            paisaStr = paisaStr.substring(2);
            String [] numReversedPaisa = paisaStr.split('');
            String[] actnumberPaisa = reverse(numReversedPaisa);
            secondHalf = convertInWords(numReversedPaisa, actnumberPaisa);
        } else {
            paisaStr = paisaStr.substring(2);
            String [] numReversedPaisa = paisaStr.split('');
            String[] actnumberPaisa = reverse(numReversedPaisa);
            secondHalf = convertInWords(numReversedPaisa, actnumberPaisa);
        }
        
        String SumOFHalves = '';
        
        if (secondHalf.length() > 4) {
            firstHalf = firstHalf.replace('Only', 'Rupess And ');
            secondHalf = secondHalf.replace('Only', 'Paisa Only');
            SumOFHalves = firstHalf + secondHalf;
        } else {
            firstHalf = firstHalf.replace('Only', 'Rupess Only');
            SumOFHalves = firstHalf;
        }
        
        // IF amount has any value
        if (SumOFHalves.length() > 5) {
            return SumOFHalves;
        } else {
            return '';
        }
    }
    
    // Method reverse the number
    public List<String> reverse(List<String> strToRev) {
        List<String> revList = new List<String>();
        for (Integer i = strToRev.size() - 1; i >= 0; i--) {
            revList.add(strToRev.get(i));
        }
        revList.add('');
        return revList;
    }
    
    public String convertInWords(String[] numRev, String[] actnum) {
        List<String> iWords = new List<String> {'Zero', ' One', ' Two', ' Three', ' Four', ' Five', ' Six', ' Seven', ' Eight', ' Nine'};
            List<String> ePlace = new List<String> {' Ten', ' Eleven', ' Twelve', ' Thirteen', ' Fourteen', ' Fifteen', ' Sixteen', ' Seventeen', ' Eighteen', ' Nineteen'};
                List<String> tensPlace = new List<String> {'dummy', ' Ten', ' Twenty', ' Thirty', ' Forty', ' Fifty', ' Sixty', ' Seventy', ' Eighty', ' Ninety' };
                    
                    Integer iWordsLength = numRev.size();
        String totalWords = '';
        List<String> inWords = new List<String>();
        for (Integer k = 0; k < iWordsLength; k++) {
            inWords.add('');
        }
        String finalWord = '';
        Integer j = 0;
        
        // Main For loop
        for (Integer i = 0; i < iWordsLength; i++) {
            
            if (i == 0) {
                if (actnum[i] == '0' || actnum[i + 1] == '1') {
                    inWords[j] = '';
                } else {
                    inWords[j] = iWords[Integer.valueof(actnum[i])];
                }
                inWords[j] = inWords[j] + ' Only';
            } else if (i == 1) {
                
                if (actnum[i] == '0') {
                    inWords[j] = '';
                } else if (actnum[i] == '1') {
                    inWords[j] = ePlace[Integer.valueof(actnum[i - 1])];
                } else {
                    inWords[j] = tensPlace[Integer.valueof(actnum[i])];
                }
            } else if (i == 2) {
                if (actnum[i] == '0') {
                    inWords[j] = '';
                } else if (actnum[i - 1] != '0' && actnum[i - 2] != '0') {
                    inWords[j] = iWords[Integer.valueof(actnum[i])] + ' Hundred and';
                } else {
                    inWords[j] = iWords[Integer.valueof(actnum[i])] + ' Hundred';
                }
            } else if (i == 3) {
                if (actnum[i] == '0' || actnum[i + 1] == '1') {
                    inWords[j] = '';
                } else {
                    inWords[j] = iWords[Integer.valueof(actnum[i])];
                }
                if (actnum[i + 1] != '0' || Integer.valueof(actnum[i]) > 0) {
                    inWords[j] = inWords[j] + ' Thousand';
                }
            } else if (i == 4) {
                
                if (actnum[i] == '0') {
                    inWords[j] = '';
                } else if (actnum[i] == '1') {
                    inWords[j] = ePlace[Integer.valueof(actnum[i - 1])];
                } else {
                    inWords[j] = tensPlace[Integer.valueof(actnum[i])];
                }
                
            } else if (i == 5) {
                if (actnum[i] == '0' || actnum[i + 1] == '1') {
                    inWords[j] = '';
                } else {
                    inWords[j] = iWords[Integer.valueof(actnum[i])];
                }
                if (actnum[i + 1] != '0' || Integer.valueof(actnum[i]) > 0) {
                    inWords[j] = inWords[j] + ' Lakh';
                }
            } else if (i == 6) {
                
                if (actnum[i] == '0') {
                    inWords[j] = '';
                } else if (actnum[i] == '1') {
                    inWords[j] = ePlace[Integer.valueof(actnum[i - 1])];
                } else {
                    inWords[j] = tensPlace[Integer.valueof(actnum[i])];
                }
                
            } else if (i == 7) {
                if (actnum[i] == '0' || actnum[i + 1] == '1' ) {
                    inWords[j] = '';
                } else {
                    inWords[j] = iWords[Integer.valueof(actnum[i])];
                }
                inWords[j] = inWords[j] + ' Crore';
            } else if (i == 8) {
                
                if (actnum[i] == '0') {
                    inWords[j] = '';
                } else if (actnum[i] == '1') {
                    inWords[j] = ePlace[Integer.valueof(actnum[i - 1])];
                } else {
                    inWords[j] = tensPlace[Integer.valueof(actnum[i])];
                }
                
            }
            
            j++;
        }
        // End of For loop
        
        // Reverse the List
        inWords = reverse(inWords);
        
        for (Integer i = 0; i < inWords.size(); i++) {
            finalWord += inWords[i];
        }
        
        return finalWord;
    }
    
}