objects/Account.object
<CustomObject>
    <fields>
        <fullName>Customer_Disc_Group__c</fullName>
        <description>This field is used to map discount and query from Discount Mapping object</description>
        <inlineHelpText>This is a Customer Discount Group</inlineHelpText>
        <label>Customer Disc. Group</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Order_Line_Item__c.object
<CustomObject>
    <fields>
        <fullName>CGST__c</fullName>
        <description>This Field store CGST Price (Price After Discount * CGST%)</description>
        <label>CGST</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Cash_Discount_CD__c</fullName>
        <description>This Field store Cash Discount ((Quantity*Unit Price)*Cash Discount %</description>
        <label>Cash Discount(CD)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Cash_Discount_Percentage__c</fullName>
        <label>Cash Discount Percentage</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Final_Price__c</fullName>
        <description>This Field store Final Price ((Quantity*Unit Price)-Total Discount )+CGST+SGST</description>
        <label>Final Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>OriPlast_Product_Price__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>OriPlast Product Price</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Product_Price__c.Oriplast_Product__c</field>
                <operation>equals</operation>
                <valueField>$Source.Ori_Plast_Product__c</valueField>
            </filterItems>
            <infoMessage>Please select a price belongs to the selected product.</infoMessage>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Product_Price__c</referenceTo>
        <relationshipLabel>Order-Line-Items</relationshipLabel>
        <relationshipName>Order_Line_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Ori_Plast_Order__c</fullName>
        <description>Lookup with Ori-plast Order</description>
        <label>Ori-Plast Order</label>
        <referenceTo>Ori_Plast_Order__c</referenceTo>
        <relationshipLabel>Order-Line-Items</relationshipLabel>
        <relationshipName>Order_Line_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Ori_Plast_Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup with Ori-plast Product</description>
        <label>Ori-Plast Product</label>
        <referenceTo>OriPlast_Product__c</referenceTo>
        <relationshipLabel>Order-Line-Items</relationshipLabel>
        <relationshipName>Order_Line_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Price_After_Discount__c</fullName>
        <description>This Field store After Discount Price ((Quantity*Unit Price)-Trade Discount - Cash Discount)</description>
        <label>Price After Discount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Quantity__c</fullName>
        <description>This is for Product quantity</description>
        <label>Quantity</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>SGST__c</fullName>
        <description>This Field store SGST price (Price After Discount * SGST%)</description>
        <label>SGST</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Special_Discount__c</fullName>
        <label>Special Discount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Trade_Discount_TD__c</fullName>
        <description>This Field store Trade Discount ((Quantity*Unit Price)*Trade Discount %)</description>
        <label>Trade Discount(TD)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Trade_Discount__c</fullName>
        <description>This Field store Trade Discount for A Product from Discount Mapping Obj. by flow</description>
        <label>Trade Discount</label>
        <precision>5</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Unit_of_Measure__c</fullName>
        <label>Unit of Measure</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Order-Line-Item</label>
    <nameField>
        <displayFormat>OLN-{000000}</displayFormat>
        <label>Order-Line-Item No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Order-Line-Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Ori_Plast_Order__c.object
<CustomObject>
    <fields>
        <fullName>Final_Order_Value__c</fullName>
        <description>This field store Final Price(Price after discount+cgst+sgst)</description>
        <inlineHelpText>Calculated price of all submitted line items.</inlineHelpText>
        <label>Total Order Value</label>
        <summarizedField>Order_Line_Item__c.Final_Price__c</summarizedField>
        <summaryForeignKey>Order_Line_Item__c.Ori_Plast_Order__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <label>Ori-Plast Order</label>
    <nameField>
        <displayFormat>ON-26-27-{000000}</displayFormat>
        <label>Ori-Plast Order No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Ori-Plast Orders</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/OriPlast_Discount_Mapping__c.object
<CustomObject>
    <fields>
        <fullName>Cash_Discount__c</fullName>
        <description>This Field Store Cash Discount For a Product</description>
        <label>Cash Discount %</label>
        <precision>6</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Discount__c</fullName>
        <description>This field stored TD For a product</description>
        <label>Trade Discount (TD) %</label>
        <precision>5</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>ItemDiscountCode_ExternalKey__c</fullName>
        <caseSensitive>true</caseSensitive>
        <description>This Field Store combined Value of (Account.Customer Disc. Group_Product.Item Disc. Group)</description>
        <externalId>true</externalId>
        <label>ItemDiscountCode_ExternalKey</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Special_Discount__c</fullName>
        <description>This field made for if in future there are special discount for a product</description>
        <label>Special Discount %</label>
        <precision>6</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <label>OriPlast Discount Mapping</label>
    <nameField>
        <label>Discount Maping Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>OriPlast Discount Mappings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/OriPlast_Product__c.object
<CustomObject>
    <fields>
        <fullName>GST_Value__c</fullName>
        <description>This Field is used to calculate GST on flow</description>
        <formula>IF( GST_Group_Code__c  = &quot;G18.00&quot;, 18,  IF(GST_Group_Code__c  = &quot;G05.00&quot;, 5, 00) )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>GST Value</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Item_Disc_Group__c</fullName>
        <description>Here the discounts are defined for specific items or item groups.</description>
        <inlineHelpText>It is used for entering Item Discount Group</inlineHelpText>
        <label>Item Disc. Group</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Length_In_Meter__c</fullName>
        <description>This field will display the length of the product in meter</description>
        <formula>TEXT(VALUE(Length__c)/10)</formula>
        <label>Length (Meter)</label>
        <type>Text</type>
    </fields>
    <label>Ori-Plast Product</label>
    <nameField>
        <label>Ori-PlastProduct Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Ori-Plast Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Product_Price__c.object
<CustomObject>
    <fields>
        <fullName>Oriplast_Product__c</fullName>
        <label>Oriplast Product</label>
        <referenceTo>OriPlast_Product__c</referenceTo>
        <relationshipLabel>Product Prices</relationshipLabel>
        <relationshipName>Product_Prices</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Quantity__c</fullName>
        <description>This field is made for lwc place order</description>
        <label>Quantity</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Unit_Price__c</fullName>
        <description>This Field Store  A product unit price</description>
        <label>Unit Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>Product Price</label>
    <nameField>
        <displayFormat>PN-{000000}</displayFormat>
        <label>Product Price Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Product Prices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/recalculateOrderClass.cls
// public with sharing class recalculateOrderClass {
    
    //     @AuraEnabled
    //     public static void recalculateOrder(Id orderId, Id accountId) {
        
        //         // 🔹 Fetch Line Items
        //         List<Order_Line_Item__c> lines = [
        //             SELECT Id, Ori_Plast_Product__c, Quantity__c,
        //                    Unit_of_Measure__c,
        //                    Trade_Discount__c, Cash_Discount_Percentage__c
        //             FROM Order_Line_Item__c
        //             WHERE Ori_Plast_Order__c = :orderId
        //         ];
        
        //         if(lines.isEmpty()) return;
        
        //         // 🔹 Fetch Account
        //         Account acc = [
        //             SELECT Id, Customer_Disc_Group__c
        //             FROM Account
        //             WHERE Id = :accountId
        //             LIMIT 1
        //         ];
        
        //         // 🔹 Collect Product Ids
        //         Set<Id> productIds = new Set<Id>();
        //         for(Order_Line_Item__c li : lines){
            //             if(li.Ori_Plast_Product__c != null){
                //                 productIds.add(li.Ori_Plast_Product__c);
            //             }
        //         }
        
        //         // 🔹 Maps
        //         Map<Id, Decimal> productPriceMap = new Map<Id, Decimal>();
        //         Map<Id, Decimal> productGSTMap = new Map<Id, Decimal>();
        //         Map<Id, Id> productPriceIdMap = new Map<Id, Id>();
        //         Map<Id, String> productDiscGroupMap = new Map<Id, String>();
        
        //         // 🔹 Fetch Product Data
        //         for(OriPlast_Product__c prod : [
        //             SELECT Id, GST_Value__c, Item_Disc_Group__c,
        //                    (SELECT Id, Unit_Price__c FROM Product_Prices__r LIMIT 1)
        //             FROM OriPlast_Product__c
        //             WHERE Id IN :productIds
        //         ]){
            
            //             if(prod.Product_Prices__r != null && !prod.Product_Prices__r.isEmpty()){
                //                 Product_Price__c priceRec = prod.Product_Prices__r[0];
                
                //                 productPriceMap.put(prod.Id, priceRec.Unit_Price__c);
                //                 productPriceIdMap.put(prod.Id, priceRec.Id);
            //             }
            
            //             productGSTMap.put(prod.Id, prod.GST_Value__c);
            //             productDiscGroupMap.put(prod.Id, prod.Item_Disc_Group__c);
        //         }
        
        //         // 🔹 Fetch Discount Mapping (IMPORTANT FIX)
        //         Map<String, OriPlast_Discount_Mapping__c> discountMap = new Map<String, OriPlast_Discount_Mapping__c>();
        
        //         for(OriPlast_Discount_Mapping__c d : [
        //             SELECT ItemDiscountCode_ExternalKey__c,
        //                    Discount__c,
        //                    Special_Discount__c,
        //                    Cash_Discount__c
        //             FROM OriPlast_Discount_Mapping__c
        //         ]){
            //             discountMap.put(d.ItemDiscountCode_ExternalKey__c, d);
        //         }
        
        //         Decimal totalOrderValue = 0;
        
        //         // 🔹 Main Loop
        //         for (Order_Line_Item__c li : lines) {
            
            //             Decimal unitPrice = productPriceMap.get(li.Ori_Plast_Product__c);
            //             Decimal gstPercent = productGSTMap.get(li.Ori_Plast_Product__c);
            
            //             if(unitPrice == null) unitPrice = 0;
            //             if(gstPercent == null) gstPercent = 0;
            
            //             Decimal qty = li.Quantity__c == null ? 0 : li.Quantity__c;
            
            //             // 🔹 BASE PRICE
            //             Decimal base = qty * unitPrice;
            
            //             // 🔥 SAFE KEY BUILD
            //             String custGroup = acc.Customer_Disc_Group__c == null ? '' : acc.Customer_Disc_Group__c;
            //             String itemGroup = productDiscGroupMap.get(li.Ori_Plast_Product__c) == null
            //                                ? ''
            //                                : productDiscGroupMap.get(li.Ori_Plast_Product__c);
            
            //             String discountKey = custGroup + '_' + itemGroup;
            
            //             System.debug('Discount Key 👉 ' + discountKey);
            
            //             Decimal tradePercent = 0;
            //             Decimal cashPercent = 0;
            
            //             // 🔥 APPLY DISCOUNT
            //             if(discountMap.containsKey(discountKey)){
                //                 OriPlast_Discount_Mapping__c d = discountMap.get(discountKey);
                
                //                 Decimal tradeDisc = d.Discount__c == null ? 0 : d.Discount__c;
                //                 Decimal specialDisc = d.Special_Discount__c == null ? 0 : d.Special_Discount__c;
                
                //                 tradePercent = tradeDisc + specialDisc;   // ✅ FIXED
                //                 cashPercent = d.Cash_Discount__c == null ? 0 : d.Cash_Discount__c;
            //             }
            //             else{
                //                 System.debug('⚠️ No discount mapping found for key: ' + discountKey);
            //             }
            
            //             // 🔹 SAVE %
            //             li.Trade_Discount__c = tradePercent;
            //             li.Cash_Discount_Percentage__c = cashPercent;
            
            //             // 🔹 TRADE DISCOUNT
            //             Decimal tradeAmount = (base * tradePercent) / 100;
            //             tradeAmount = tradeAmount.setScale(2);   // ✅ ROUNDING FIX
            //             li.Trade_Discount_TD__c = tradeAmount;
            
            //             Decimal afterTrade = base - tradeAmount;
            
            //             // 🔹 CASH DISCOUNT
            //             Decimal cashAmount = (afterTrade * cashPercent) / 100;
            //             cashAmount = cashAmount.setScale(2);     // ✅ ROUNDING FIX
            //             li.Cash_Discount_CD__c = cashAmount;
            
            //             Decimal afterCash = afterTrade - cashAmount;
            
            //             // 🔹 GST
            //             Decimal gst = (afterCash * gstPercent) / 100;
            //             gst = gst.setScale(2);
            
            //             // 🔹 FINAL VALUES
            //             li.Price_After_Discount__c = afterCash.setScale(2);
            //             li.Final_Price__c = (afterCash + gst).setScale(2);
            //             li.CGST__c = (gst / 2).setScale(2);
            //             li.SGST__c = (gst / 2).setScale(2);
            
            //             // 🔹 SET PRODUCT PRICE LOOKUP
            //             li.OriPlast_Product_Price__c = productPriceIdMap.get(li.Ori_Plast_Product__c);
            
            //             totalOrderValue += li.Final_Price__c;
        //         }
        
        //         // 🔹 SAVE
        //         update lines;
        
        //         // 🔹 OPTIONAL ORDER UPDATE
        //         /*
        //         update new Ori_Plast_Order__c(
        //             Id = orderId,
        //             Final_Order_Value__c = totalOrderValue
        //         );
        //         */
    //     }
// }

// public with sharing class recalculateOrderClass {
    
    //     @AuraEnabled
    //     public static void recalculateOrder(Id orderId, Id accountId) {
        
        //         // 🔹 Fetch Line Items
        //         List<Order_Line_Item__c> lines = [
        //             SELECT Id, Ori_Plast_Product__c, Quantity__c,
        //                    Unit_of_Measure__c,
        //                    Trade_Discount__c, Cash_Discount_Percentage__c
        //             FROM Order_Line_Item__c
        //             WHERE Ori_Plast_Order__c = :orderId
        //         ];
        
        //         if(lines.isEmpty()) return;
        
        //         // 🔹 Fetch Account (Customer Discount Group)
        //         Account acc = [
        //             SELECT Id, Customer_Disc_Group__c
        //             FROM Account
        //             WHERE Id = :accountId
        //             LIMIT 1
        //         ];
        
        //         // 🔹 Collect Product Ids
        //         Set<Id> productIds = new Set<Id>();
        //         for(Order_Line_Item__c li : lines){
            //             if(li.Ori_Plast_Product__c != null){
                //                 productIds.add(li.Ori_Plast_Product__c);
            //             }
        //         }
        
        //         // 🔹 Maps
        //         Map<Id, Decimal> productPriceMap = new Map<Id, Decimal>();
        //         Map<Id, Decimal> productGSTMap = new Map<Id, Decimal>();
        //         Map<Id, Id> productPriceIdMap = new Map<Id, Id>();
        //         Map<Id, String> productDiscGroupMap = new Map<Id, String>();
        
        //         // 🔹 Fetch Product + Price + Discount Group
        //         for(OriPlast_Product__c prod : [
        //             SELECT Id, GST_Value__c, Item_Disc_Group__c,
        //                    (SELECT Id, Unit_Price__c FROM Product_Prices__r LIMIT 1)
        //             FROM OriPlast_Product__c
        //             WHERE Id IN :productIds
        //         ]){
            
            //             if(prod.Product_Prices__r != null && !prod.Product_Prices__r.isEmpty()){
                //                 Product_Price__c priceRec = prod.Product_Prices__r[0];
                
                //                 productPriceMap.put(prod.Id, priceRec.Unit_Price__c);
                //                 productPriceIdMap.put(prod.Id, priceRec.Id);
            //             }
            
            //             productGSTMap.put(prod.Id, prod.GST_Value__c);
            //             productDiscGroupMap.put(prod.Id, prod.Item_Disc_Group__c);
        //         }
        
        //         // 🔹 Fetch Discount Mapping
        //         Map<String, OriPlast_Discount_Mapping__c> discountMap = new Map<String, OriPlast_Discount_Mapping__c>();
        
        //         for(OriPlast_Discount_Mapping__c d : [
        //             SELECT ItemDiscountCode_ExternalKey__c, Discount__c, Cash_Discount__c
        //             FROM OriPlast_Discount_Mapping__c
        //         ]){
            //             discountMap.put(d.ItemDiscountCode_ExternalKey__c, d);
        //         }
        
        //         Decimal totalOrderValue = 0;
        
        //         // 🔹 Calculation Loop
        //         for (Order_Line_Item__c li : lines) {
            
            //             Decimal unitPrice = productPriceMap.get(li.Ori_Plast_Product__c);
            //             Decimal gstPercent = productGSTMap.get(li.Ori_Plast_Product__c);
            
            //             if(unitPrice == null) unitPrice = 0;
            //             if(gstPercent == null) gstPercent = 0;
            
            //             Decimal qty = li.Quantity__c == null ? 0 : li.Quantity__c;
            
            //             // 🔹 BASE PRICE
            //             Decimal base = qty * unitPrice;
            
            //             // 🔥 CORRECT DISCOUNT KEY (MAIN FIX)
            //             String custGroup = acc.Customer_Disc_Group__c;
            //             String itemGroup = productDiscGroupMap.get(li.Ori_Plast_Product__c);
            
            //             String discountKey = custGroup + '_' + itemGroup;
            
            //             Decimal tradePercent = 0;
            //             Decimal cashPercent = 0;
            
            //             if(discountMap.containsKey(discountKey)){
                //                 OriPlast_Discount_Mapping__c d = discountMap.get(discountKey);
                
                //                 tradePercent = d.Discount__c == null ? 0 : d.Discount__c;
                //                 cashPercent = d.Cash_Discount__c == null ? 0 : d.Cash_Discount__c;
            //             }
            
            //             // 🔹 Save % on line
            //             li.Trade_Discount__c = tradePercent;
            //             li.Cash_Discount_Percentage__c = cashPercent;
            
            //             // 🔹 TRADE DISCOUNT
            //             Decimal tradeAmount = (base * tradePercent) / 100;
            //             li.Trade_Discount_TD__c = tradeAmount;
            
            //             Decimal afterTrade = base - tradeAmount;
            
            //             // 🔹 CASH DISCOUNT
            //             Decimal cashAmount = (afterTrade * cashPercent) / 100;
            //             li.Cash_Discount_CD__c = cashAmount;
            
            //             Decimal afterCash = afterTrade - cashAmount;
            
            //             // 🔹 GST
            //             Decimal gst = (afterCash * gstPercent) / 100;
            
            //             // 🔹 FINAL VALUES
            //             li.Price_After_Discount__c = afterCash;
            //             li.Final_Price__c = afterCash + gst;
            //             li.CGST__c = gst / 2;
            //             li.SGST__c = gst / 2;
            
            //             // 🔹 SET PRODUCT PRICE LOOKUP
            //             li.OriPlast_Product_Price__c = productPriceIdMap.get(li.Ori_Plast_Product__c);
            
            //             totalOrderValue += li.Final_Price__c;
        //         }
        
        //         // 🔹 Save Line Items
        //         update lines;
        
        //         // 🔹 Optional Order Update
        //         /*
        //         update new Ori_Plast_Order__c(
        //             Id = orderId,
        //             Final_Order_Value__c = totalOrderValue
        //         );
        //         */
    //     }
// }


public with sharing class recalculateOrderClass {
    
    @AuraEnabled
    public static void recalculateOrder(Id orderId, Id accountId) {
        
        // 🔹 Fetch Line Items
        List<Order_Line_Item__c> lines = [
            SELECT Id, Ori_Plast_Product__c, Quantity__c,
                   Unit_of_Measure__c,
                   Trade_Discount__c, Cash_Discount_Percentage__c
            FROM Order_Line_Item__c
            WHERE Ori_Plast_Order__c = :orderId
        ];
        
        if(lines.isEmpty()) return;
        
        // 🔹 Fetch Account
        Account acc = [
            SELECT Id, Customer_Disc_Group__c
            FROM Account
            WHERE Id = :accountId
            LIMIT 1
        ];
        
        // 🔹 Collect Product Ids
        Set<Id> productIds = new Set<Id>();
        for(Order_Line_Item__c li : lines){
            if(li.Ori_Plast_Product__c != null){
                productIds.add(li.Ori_Plast_Product__c);
            }
        }
        
        // 🔹 MAPS
        Map<Id, Decimal> productPriceMap = new Map<Id, Decimal>();
        Map<Id, Decimal> productGSTMap = new Map<Id, Decimal>();
        Map<Id, Id> productPriceIdMap = new Map<Id, Id>();
        Map<Id, String> productDiscGroupMap = new Map<Id, String>();
        Map<Id, Decimal> productLengthMap = new Map<Id, Decimal>(); // ✅ FIX
        
        // 🔹 FETCH PRODUCT DATA
        for(OriPlast_Product__c prod : [
            SELECT Id, GST_Value__c, Item_Disc_Group__c, Length_In_Meter__c,
                   (SELECT Id, Unit_Price__c FROM Product_Prices__r LIMIT 1)
            FROM OriPlast_Product__c
            WHERE Id IN :productIds
        ]){
            
            // ✅ CORRECT LENGTH STORE
            String length = prod.Length_In_Meter__c == null ? '0.0' : prod.Length_In_Meter__c;
            productLengthMap.put(prod.Id, Decimal.valueOf(length));
            
            if(prod.Product_Prices__r != null && !prod.Product_Prices__r.isEmpty()){
                Product_Price__c priceRec = prod.Product_Prices__r[0];
                
                productPriceMap.put(prod.Id, priceRec.Unit_Price__c);
                productPriceIdMap.put(prod.Id, priceRec.Id);
            }
            
            productGSTMap.put(prod.Id, prod.GST_Value__c);
            productDiscGroupMap.put(prod.Id, prod.Item_Disc_Group__c);
        }
        
        // 🔹 DISCOUNT MAP
        Map<String, OriPlast_Discount_Mapping__c> discountMap = new Map<String, OriPlast_Discount_Mapping__c>();
        
        for(OriPlast_Discount_Mapping__c d : [
            SELECT ItemDiscountCode_ExternalKey__c,
                   Discount__c,
                   Special_Discount__c,
                   Cash_Discount__c
            FROM OriPlast_Discount_Mapping__c
        ]){
            discountMap.put(d.ItemDiscountCode_ExternalKey__c, d);
        }
        
        Decimal totalOrderValue = 0;
        
        // 🔹 MAIN CALCULATION LOOP
        for (Order_Line_Item__c li : lines) {
            
            Decimal unitPrice = productPriceMap.get(li.Ori_Plast_Product__c);
            Decimal gstPercent = productGSTMap.get(li.Ori_Plast_Product__c);
            
            if(unitPrice == null) unitPrice = 0;
            if(gstPercent == null) gstPercent = 0;
            
            Decimal qty = li.Quantity__c == null ? 0 : li.Quantity__c;
            
            // =========================
            // ✅ CORRECT BASE LOGIC
            // =========================
            Decimal base = 0;
            
            Decimal length = productLengthMap.containsKey(li.Ori_Plast_Product__c)
                ? productLengthMap.get(li.Ori_Plast_Product__c)
                : 0.0;
            
            String uom = li.Unit_of_Measure__c == null ? '' : li.Unit_of_Measure__c;
            
            if(uom == 'MTR' && length > 0){
                base = qty * length * unitPrice;
            } else {
                base = qty * unitPrice;
            }
            
            // =========================
            // 🔹 DISCOUNT KEY
            // =========================
            String custGroup = acc.Customer_Disc_Group__c == null ? '' : acc.Customer_Disc_Group__c;
            String itemGroup = productDiscGroupMap.get(li.Ori_Plast_Product__c) == null
                ? '' : productDiscGroupMap.get(li.Ori_Plast_Product__c);
            
            String discountKey = custGroup + '_' + itemGroup;
            
            Decimal tradePercent = 0;
            Decimal cashPercent = 0;
            
            if(discountMap.containsKey(discountKey)){
                OriPlast_Discount_Mapping__c d = discountMap.get(discountKey);
                
                // ✅ TRADE = Discount + Special Discount
                tradePercent = (d.Discount__c == null ? 0 : d.Discount__c)
                             + (d.Special_Discount__c == null ? 0 : d.Special_Discount__c);
                
                cashPercent = d.Cash_Discount__c == null ? 0 : d.Cash_Discount__c;
            }
            
            // 🔹 SAVE %
            li.Trade_Discount__c = tradePercent;
            li.Cash_Discount_Percentage__c = cashPercent;
            
            // 🔹 TRADE DISCOUNT
            Decimal tradeAmount = (base * tradePercent) / 100;
            li.Trade_Discount_TD__c = tradeAmount.setScale(2);
            
            Decimal afterTrade = base - tradeAmount;
            
            // 🔹 CASH DISCOUNT
            Decimal cashAmount = (afterTrade * cashPercent) / 100;
            li.Cash_Discount_CD__c = cashAmount.setScale(2);
            
            Decimal afterCash = afterTrade - cashAmount;
            
            // 🔹 GST
            Decimal gst = (afterCash * gstPercent) / 100;
            gst = gst.setScale(2);
            
            // 🔹 FINAL VALUES
            li.Price_After_Discount__c = afterCash.setScale(2);
            li.Final_Price__c = (afterCash + gst).setScale(2);
            li.CGST__c = (gst / 2).setScale(2);
            li.SGST__c = (gst / 2).setScale(2);
            
            // 🔹 SET PRICE LOOKUP
            li.OriPlast_Product_Price__c = productPriceIdMap.get(li.Ori_Plast_Product__c);
            
            totalOrderValue += li.Final_Price__c;
        }
        
        // 🔹 UPDATE
        update lines;
    }
}