objects/Account.object
<CustomObject>
    <fields>
        <fullName>Account_External_Key__c</fullName>
        <description>This Field used as a external id for data loading</description>
        <externalId>true</externalId>
        <label>Account External Key</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Invoice__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Dealer</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Invoices</relationshipLabel>
        <relationshipName>Ori_Plast_Invoices</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Distributor__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Distributor</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Invoices (Distributor)</relationshipLabel>
        <relationshipName>Invoices</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Invoice_Number__c</fullName>
        <description>External unique Id coming from JSON.</description>
        <label>Invoice Number</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Submitted</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Invoice</label>
    <nameField>
        <displayFormat>INV-{000000}</displayFormat>
        <label>Invoice Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Invoice_Line_Item__c.object
<CustomObject>
    <fields>
        <fullName>Final_Price__c</fullName>
        <description>This Field store Final Price from Integration</description>
        <label>Final Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Ori_Plast_Invoice__c</fullName>
        <label>Ori-Plast Invoice</label>
        <referenceTo>Invoice__c</referenceTo>
        <relationshipName>Ori_plast_Invoice_Line_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Quantity__c</fullName>
        <description>This Field store Quantity from Integration</description>
        <label>Quantity</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Rate__c</fullName>
        <label>Rate</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>SKU__c</fullName>
        <label>Item Description</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Total_Discount_Percentage__c</fullName>
        <label>Total Discount %</label>
        <precision>5</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Unit_of_Measure__c</fullName>
        <description>This Field store Unit of Measure from Integration</description>
        <label>UOM</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>Invoice Line Item</label>
    <nameField>
        <displayFormat>ILN-{0000000}</displayFormat>
        <label>Invoice-Line-Item No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoice Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/OriPlast_Product__c.object
<CustomObject>
    <fields>
        <fullName>Base_Unit_of_Measure__c</fullName>
        <description>This field is used for entering a unit of measurement adopted for a base quantity</description>
        <inlineHelpText>It is used for entering Base unit of measure.</inlineHelpText>
        <label>Base Unit of Measure</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Category_Picklist__c</fullName>
        <description>This is a picklist field for choosing type of Category for the customers who search for products.</description>
        <inlineHelpText>This is a picklist field for choosing type of category.</inlineHelpText>
        <label>Category</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>P1</fullName>
                    <label>PVC Pipe ASTM-D-1785, PVC ASTM (Schdule)</label>
                </value>
                <value>
                    <fullName>P2</fullName>
                    <label>PVC Grey pipes as per IS : 4985,UPVC IS 4985</label>
                </value>
                <value>
                    <fullName>P3</fullName>
                    <label>CASING &amp; PVC Casing Pipes as per IS : 12818</label>
                </value>
                <value>
                    <fullName>P4</fullName>
                    <label>PVC SCREEN &amp; PVC Screen Pipes as per IS : 12818</label>
                </value>
                <value>
                    <fullName>P5</fullName>
                    <label>PVC GARDEN HOSE PIPE</label>
                </value>
                <value>
                    <fullName>P6</fullName>
                    <label>PVC SWR pipes &amp; fittings as per IS:13592</label>
                </value>
                <value>
                    <fullName>P7</fullName>
                    <label>PVC Column Pipe</label>
                </value>
                <value>
                    <fullName>P8</fullName>
                    <label>PVC Submersible</label>
                </value>
                <value>
                    <fullName>P9</fullName>
                    <label>CPVC Pipe</label>
                </value>
                <value>
                    <fullName>PF</fullName>
                    <label>PVC Fittings</label>
                </value>
                <value>
                    <fullName>H1</fullName>
                    <label>HDPE Pipe IS 4984 (Black)</label>
                </value>
                <value>
                    <fullName>H2</fullName>
                    <label>HDPE Pipe IS 14333 (Black)</label>
                </value>
                <value>
                    <fullName>H3</fullName>
                    <label>GI STANDERD &amp; PLB Duct Pipe</label>
                </value>
                <value>
                    <fullName>H4</fullName>
                    <label>HDPE IS 4427 (Blue/Black)</label>
                </value>
                <value>
                    <fullName>H5</fullName>
                    <label>HDPE 4984-2016</label>
                </value>
                <value>
                    <fullName>HF</fullName>
                    <label>HDPE Fittings</label>
                </value>
                <value>
                    <fullName>DF</fullName>
                    <label>Direct Action Hand Pump Fittings</label>
                </value>
                <value>
                    <fullName>M1</fullName>
                    <label>MDPE Pipe &amp; MDPE IS 14885</label>
                </value>
                <value>
                    <fullName>M2</fullName>
                    <label>MDPE pipe &amp; MDPE IS 4427</label>
                </value>
                <value>
                    <fullName>SL</fullName>
                    <label>Solvent Cement</label>
                </value>
                <value>
                    <fullName>NI</fullName>
                    <label>PVC SWR pipes &amp; fittings (non-standard)</label>
                </value>
                <value>
                    <fullName>DP</fullName>
                    <label>Direct Action Hand Pump Set</label>
                </value>
                <value>
                    <fullName>H6</fullName>
                    <label>PPR</label>
                </value>
                <value>
                    <fullName>H7</fullName>
                    <label>HDPE Copper Wire</label>
                </value>
                <value>
                    <fullName>M3</fullName>
                    <label>PE PIPE(MDPE)</label>
                </value>
                <value>
                    <fullName>MF</fullName>
                    <label>MDPE Fittings</label>
                </value>
                <value>
                    <fullName>OF</fullName>
                    <label>OPVC Fittings</label>
                </value>
                <value>
                    <fullName>OP</fullName>
                    <label>OPVC Pipe</label>
                </value>
                <value>
                    <fullName>WT</fullName>
                    <label>WATER TANK and FITTINGS</label>
                </value>
                <value>
                    <fullName>TW</fullName>
                    <isActive>false</isActive>
                    <label>ASTM-D 1785 Push type White, Solvent Ciment Type</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Product_Category_Code_Picklist__c</fullName>
        <description>This picklist field is used for choosing code of a category of a product</description>
        <inlineHelpText>It is used for choosing Product Category Code.</inlineHelpText>
        <label>Product Category Code</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>PVC</fullName>
                    <default>true</default>
                    <label>PVC</label>
                </value>
                <value>
                    <fullName>HDPE</fullName>
                </value>
                <value>
                    <fullName>MDPE</fullName>
                </value>
                <value>
                    <fullName>Fabricated</fullName>
                </value>
                <value>
                    <fullName>Moulding</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Sub_Category_Picklist__c</fullName>
        <description>This is kind of picklist for choosing Sub Category of a product that is nested in another category.</description>
        <inlineHelpText>It is used for choosing Sub Category of a product.</inlineHelpText>
        <label>Sub Category</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Category_Picklist__c</controllingField>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>ASTM</fullName>
                </value>
                <value>
                    <fullName>CLASS1 (SDR11)</fullName>
                </value>
                <value>
                    <fullName>ISO 4427 Fittings</fullName>
                </value>
                <value>
                    <fullName>Male Thread</fullName>
                </value>
                <value>
                    <fullName>Pipe Grade PE 63</fullName>
                </value>
                <value>
                    <fullName>SDR 41</fullName>
                </value>
                <value>
                    <fullName>Single Socket</fullName>
                </value>
                <value>
                    <fullName>Pipe Grade PE 80</fullName>
                </value>
                <value>
                    <fullName>SDR 33</fullName>
                </value>
                <value>
                    <fullName>Bell End</fullName>
                </value>
                <value>
                    <fullName>CLASS2 (SDR 13.5)</fullName>
                </value>
                <value>
                    <fullName>Double Socket</fullName>
                </value>
                <value>
                    <fullName>IS 14333 Fittings</fullName>
                </value>
                <value>
                    <fullName>Male / Female Thread</fullName>
                </value>
                <value>
                    <fullName>UPVC</fullName>
                </value>
                <value>
                    <fullName>SDR 26</fullName>
                </value>
                <value>
                    <fullName>Pipe Grade PE 100</fullName>
                </value>
                <value>
                    <fullName>Plain End</fullName>
                </value>
                <value>
                    <fullName>Push Type</fullName>
                </value>
                <value>
                    <fullName>Sliding Socket</fullName>
                </value>
                <value>
                    <fullName>SWR</fullName>
                </value>
                <value>
                    <fullName>SDR 21</fullName>
                </value>
                <value>
                    <fullName>Cam Lock</fullName>
                </value>
                <value>
                    <fullName>CPVC</fullName>
                </value>
                <value>
                    <fullName>Flush Joint</fullName>
                </value>
                <value>
                    <fullName>SDR 17</fullName>
                </value>
                <value>
                    <fullName>LED &amp; TIN FREE</fullName>
                </value>
                <value>
                    <fullName>SDR 13.6</fullName>
                </value>
                <value>
                    <fullName>SDR 11</fullName>
                </value>
                <value>
                    <fullName>SDR 9</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Ori-Plast Product</label>
    <nameField>
        <label>Ori-PlastProduct Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Ori-Plast Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Product_Transformation_Table__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Look Up with Account</description>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Products Transformation Table</relationshipLabel>
        <relationshipName>Products_Transformation_Table</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Product Transformation Table</label>
    <nameField>
        <displayFormat>DPM-{000000}</displayFormat>
        <label>Product Transformation Table</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Products Transformation Table</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/InvoiceLineItmUpdateOriPlastProdBtchTest.cls
@isTest
public class InvoiceLineItmUpdateOriPlastProdBtchTest {
    @testSetup
  static void setupData() {
        Account distributorAcc = new Account();
        distributorAcc.Account_External_Key__c = 'CUSBLS0450';
        distributorAcc.Name = 'RASHMI AGENCY - (2023-24)';
        distributorAcc.Type = 'Distributor';
        insert distributorAcc;

        Invoice__c invoiceRecord = new Invoice__c();
        invoiceRecord.Invoice_Number__c = 'RA/T-833/24-25';
        invoiceRecord.Status__c = 'Submitted';
        invoiceRecord.Account__c = distributorAcc.Id;
        invoiceRecord.Distributor__c = distributorAcc.Id;
        insert invoiceRecord;

        
        Invoice_Line_Item__c lineItemRecord = new Invoice_Line_Item__c();
        lineItemRecord.Ori_Plast_Invoice__c = invoiceRecord.Id;
        lineItemRecord.Quantity__c = 10;
        lineItemRecord.Unit_of_Measure__c = 'mtr';
        lineItemRecord.Rate__c = 120;
        lineItemRecord.Total_Discount_Percentage__c = 0;
        lineItemRecord.Final_Price__c = 100;
        lineItemRecord.SKU__c = 'UPVC Pipe 1 1/2" CM Blue M/F 3M Ori';
        insert lineItemRecord;

        OriPlast_Product__c Oproduct = new OriPlast_Product__c(
        Name = '90 mm 4kgf/sq cm UPVC Pipe Plain End 5 Mtr',
        Base_Unit_of_Measure__c = 'PCS',
        Category_Picklist__c = 'P2',
        Product_Category_Code_Picklist__c = 'PVC',
        Sub_Category_Picklist__c = 'Plain End',
        Item_Disc_Group__c = 'PVCPI-4985',
        OriPlast_Product_Unique_Key__c = 'FP201PN040GY00500090'
        );
        insert Oproduct;

        Product_Transformation_Table__c ptr = new Product_Transformation_Table__c();
        ptr.Account__c = distributorAcc.Id;
        ptr.Ori_Plast_Product__c = Oproduct.Id;
        ptr.Tally_Item_Description__c = 'UPVC Pipe 1 1/2" CM Blue M/F 3M Ori';
        insert ptr;
    }

        @isTest
    static void batchExecutionTest() {
        Test.startTest();

        InvoiceLineItmUpdateOriPlastProductBatch batchJob = new InvoiceLineItmUpdateOriPlastProductBatch();
        Database.executeBatch(batchJob, 2);

        Test.stopTest();

        Invoice_Line_Item__c updatedLineItem = [SELECT Id, Ori_Plast_Product__c FROM Invoice_Line_Item__c WHERE SKU__c = 'UPVC Pipe 1 1/2" CM Blue M/F 3M Ori'];
        OriPlast_Product__c expectedProduct = [SELECT Id FROM OriPlast_Product__c WHERE Name = '90 mm 4kgf/sq cm UPVC Pipe Plain End 5 Mtr'];

        System.assertEquals(expectedProduct.Id, updatedLineItem.Ori_Plast_Product__c, 'The Ori_Plast_Product__c should have been updated to the corresponding product.');
    }

    /* @isTest
    static void testScheduledExecution() {
        Test.startTest();

        String sch = '0 0 0 15 3 ? 2024'; 
        InvoiceLineItmUpdateOriPlastProductBatch schedulableBatch = new InvoiceLineItmUpdateOriPlastProductBatch();
        system.schedule('TestScheduledBatch', sch, schedulableBatch);

        Test.stopTest();

        Integer jobCount = [SELECT COUNT() FROM AsyncApexJob WHERE JobType = 'BatchApex' AND Status = 'Completed'];
        System.assert(jobCount > 0, 'The batch job should have completed successfully.');
    }*/


}