objects/Integration_Log__c.object
<CustomObject>
    <fields>
        <fullName>Class_Name__c</fullName>
        <description>This field stores the name of the class from where the integration is launched</description>
        <label>Class Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Request_Body__c</fullName>
        <description>This field holds the value of the request received</description>
        <label>Request Body</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Response_Body__c</fullName>
        <description>This field holds the response created</description>
        <label>Response Body</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <description>The direction of the call is stored in this field</description>
        <label>Type</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <label>Integration Log</label>
    <nameField>
        <displayFormat>INT-{0000}</displayFormat>
        <label>Integration Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Integration Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Tally_Token__c.object
<CustomObject>
    <description>This object holds the tally tokens generated</description>
    <fields>
        <fullName>Tally_Token__c</fullName>
        <description>This field holds the token generated by tally</description>
        <label>Tally Token</label>
        <length>200</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Tally Token</label>
    <nameField>
        <displayFormat>TT-{0000}</displayFormat>
        <label>Tally Token Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Tally tokens</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/TallyTokenGeneration.cls
@RestResource(urlMapping='/tallytokengeneration/*')
global class TallyTokenGeneration {

    @HttpPost
    global static void getToken(){
        String reqBody = RestContext.request.requestBody.toString();
        Map<String,Object> obj = (Map<String,Object>) JSON.deserializeUntyped(reqBody);   
        Map<String,Object> getTokenObj = (Map<String,Object>)obj.get('TOKENDETAILS');     
        String token = getTokenObj.get('TOKEN').toString();
               
		if(!String.isBlank(token)){
            Tally_Token__c tt = new Tally_Token__c();
            tt.Tally_Token__c = token;
            insert tt;

            RestContext.response.addHeader('Content-Type', 'application/json');
            RestContext.response.responseBody = Blob.valueOf('{"status": "successfuly save token"}');
        }
        else{
            RestContext.response.addHeader('Content-Type', 'application/json');
            RestContext.response.responseBody = Blob.valueOf('{"status": "token is not provided"}');
        }

		Integration_Log__c intLog = new Integration_Log__c(
            Class_Name__c = 'TallyTokenGeneration',
            Request_Body__c = reqBody,
            Response_Body__c = RestContext.response.responseBody.toString(),
            Type__c = 'Inbound'
        );
        
		Database.insert(intLog);  
    }
}