objects/Invoice__c.object
<CustomObject>
    <fields>
        <fullName>Dealer_Name__c</fullName>
        <description>This is the text field getting value from JSON Data of the Staging Record</description>
        <label>Dealer Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Distributor__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Distributor</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Invoices (Distributor)</relationshipLabel>
        <relationshipName>Invoices</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Invoice_Date__c</fullName>
        <label>Invoice Date Text</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Invoice_Number__c</fullName>
        <description>External unique Id coming from JSON.</description>
        <label>Invoice Number</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>Invoice</label>
    <nameField>
        <displayFormat>INV-{000000}</displayFormat>
        <label>Invoice Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Invoice_Line_Item__c.object
<CustomObject>
    <fields>
        <fullName>Final_Price__c</fullName>
        <description>This Field store Final Price from Integration</description>
        <label>Final Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Invoice_No__c</fullName>
        <description>This Field store Invoice No. from Integration</description>
        <externalId>true</externalId>
        <label>Invoice No.</label>
        <length>250</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Ori_Plast_Invoice__c</fullName>
        <label>Ori-Plast Invoice</label>
        <referenceTo>Invoice__c</referenceTo>
        <relationshipName>Ori_plast_Invoice_Line_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Ori_Plast_Product_Name__c</fullName>
        <description>This Field is used to show Ori-Plast Product name</description>
        <formula>Ori_Plast_Product__r.Name</formula>
        <label>Ori-Plast Product Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Ori_Plast_Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Ori-Plast Product</label>
        <referenceTo>OriPlast_Product__c</referenceTo>
        <relationshipName>Ori_plast_Invoice_Line_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Quantity__c</fullName>
        <description>This Field store Quantity from Integration</description>
        <label>Quantity</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>SKU__c</fullName>
        <label>Item Description</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Unit_of_Measure__c</fullName>
        <description>This Field store Unit of Measure from Integration</description>
        <label>UOM</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>Invoice Line Item</label>
    <nameField>
        <displayFormat>ILN-{0000000}</displayFormat>
        <label>Invoice-Line-Item No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoice Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/OriPlast_Product__c.object
<CustomObject>
    <fields>
        <fullName>Category_Picklist__c</fullName>
        <description>This is a picklist field for choosing type of Category for the customers who search for products.</description>
        <inlineHelpText>This is a picklist field for choosing type of category.</inlineHelpText>
        <label>Category</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>P1</fullName>
                    <label>PVC Pipe ASTM-D-1785, PVC ASTM (Schdule)</label>
                </value>
                <value>
                    <fullName>P2</fullName>
                    <label>PVC Grey pipes as per IS : 4985,UPVC IS 4985</label>
                </value>
                <value>
                    <fullName>P3</fullName>
                    <label>CASING &amp; PVC Casing Pipes as per IS : 12818</label>
                </value>
                <value>
                    <fullName>P4</fullName>
                    <label>PVC SCREEN &amp; PVC Screen Pipes as per IS : 12818</label>
                </value>
                <value>
                    <fullName>P5</fullName>
                    <label>PVC GARDEN HOSE PIPE</label>
                </value>
                <value>
                    <fullName>P6</fullName>
                    <label>PVC SWR pipes &amp; fittings as per IS:13592</label>
                </value>
                <value>
                    <fullName>P7</fullName>
                    <label>PVC Column Pipe</label>
                </value>
                <value>
                    <fullName>P8</fullName>
                    <label>PVC Submersible</label>
                </value>
                <value>
                    <fullName>P9</fullName>
                    <label>CPVC Pipe</label>
                </value>
                <value>
                    <fullName>PF</fullName>
                    <label>PVC Fittings</label>
                </value>
                <value>
                    <fullName>H1</fullName>
                    <label>HDPE Pipe IS 4984 (Black)</label>
                </value>
                <value>
                    <fullName>H2</fullName>
                    <label>HDPE Pipe IS 14333 (Black)</label>
                </value>
                <value>
                    <fullName>H3</fullName>
                    <label>GI STANDERD &amp; PLB Duct Pipe</label>
                </value>
                <value>
                    <fullName>H4</fullName>
                    <label>HDPE IS 4427 (Blue/Black)</label>
                </value>
                <value>
                    <fullName>H5</fullName>
                    <label>HDPE 4984-2016</label>
                </value>
                <value>
                    <fullName>HF</fullName>
                    <label>HDPE Fittings</label>
                </value>
                <value>
                    <fullName>DF</fullName>
                    <label>Direct Action Hand Pump Fittings</label>
                </value>
                <value>
                    <fullName>M1</fullName>
                    <label>MDPE Pipe &amp; MDPE IS 14885</label>
                </value>
                <value>
                    <fullName>M2</fullName>
                    <label>MDPE pipe &amp; MDPE IS 4427</label>
                </value>
                <value>
                    <fullName>SL</fullName>
                    <label>Solvent Cement</label>
                </value>
                <value>
                    <fullName>NI</fullName>
                    <label>PVC SWR pipes &amp; fittings (non-standard)</label>
                </value>
                <value>
                    <fullName>DP</fullName>
                    <label>Direct Action Hand Pump Set</label>
                </value>
                <value>
                    <fullName>H6</fullName>
                    <label>PPR</label>
                </value>
                <value>
                    <fullName>H7</fullName>
                    <label>HDPE Copper Wire</label>
                </value>
                <value>
                    <fullName>M3</fullName>
                    <label>PE PIPE(MDPE)</label>
                </value>
                <value>
                    <fullName>MF</fullName>
                    <label>MDPE Fittings</label>
                </value>
                <value>
                    <fullName>OF</fullName>
                    <label>OPVC Fittings</label>
                </value>
                <value>
                    <fullName>OP</fullName>
                    <label>OPVC Pipe</label>
                </value>
                <value>
                    <fullName>WT</fullName>
                    <label>WATER TANK and FITTINGS</label>
                </value>
                <value>
                    <fullName>TW</fullName>
                    <isActive>false</isActive>
                    <label>ASTM-D 1785 Push type White, Solvent Ciment Type</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Sub_Category_Picklist__c</fullName>
        <description>This is kind of picklist for choosing Sub Category of a product that is nested in another category.</description>
        <inlineHelpText>It is used for choosing Sub Category of a product.</inlineHelpText>
        <label>Sub Category</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Category_Picklist__c</controllingField>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>ASTM</fullName>
                </value>
                <value>
                    <fullName>CLASS1 (SDR11)</fullName>
                </value>
                <value>
                    <fullName>ISO 4427 Fittings</fullName>
                </value>
                <value>
                    <fullName>Male Thread</fullName>
                </value>
                <value>
                    <fullName>Pipe Grade PE 63</fullName>
                </value>
                <value>
                    <fullName>SDR 41</fullName>
                </value>
                <value>
                    <fullName>Single Socket</fullName>
                </value>
                <value>
                    <fullName>Pipe Grade PE 80</fullName>
                </value>
                <value>
                    <fullName>SDR 33</fullName>
                </value>
                <value>
                    <fullName>Bell End</fullName>
                </value>
                <value>
                    <fullName>CLASS2 (SDR 13.5)</fullName>
                </value>
                <value>
                    <fullName>Double Socket</fullName>
                </value>
                <value>
                    <fullName>IS 14333 Fittings</fullName>
                </value>
                <value>
                    <fullName>Male / Female Thread</fullName>
                </value>
                <value>
                    <fullName>UPVC</fullName>
                </value>
                <value>
                    <fullName>SDR 26</fullName>
                </value>
                <value>
                    <fullName>Pipe Grade PE 100</fullName>
                </value>
                <value>
                    <fullName>Plain End</fullName>
                </value>
                <value>
                    <fullName>Push Type</fullName>
                </value>
                <value>
                    <fullName>Sliding Socket</fullName>
                </value>
                <value>
                    <fullName>SWR</fullName>
                </value>
                <value>
                    <fullName>SDR 21</fullName>
                </value>
                <value>
                    <fullName>Cam Lock</fullName>
                </value>
                <value>
                    <fullName>CPVC</fullName>
                </value>
                <value>
                    <fullName>Flush Joint</fullName>
                </value>
                <value>
                    <fullName>SDR 17</fullName>
                </value>
                <value>
                    <fullName>LED &amp; TIN FREE</fullName>
                </value>
                <value>
                    <fullName>SDR 13.6</fullName>
                </value>
                <value>
                    <fullName>SDR 11</fullName>
                </value>
                <value>
                    <fullName>SDR 9</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Ori-Plast Product</label>
    <nameField>
        <label>Ori-PlastProduct Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Ori-Plast Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/InvoiceCSVService.cls
// --------------------- NEW CLASS: InvoiceCSVService.cls ---------------------
public class InvoiceCSVService {

    public static Blob generateWeeklyCSV(Id distributorId) {

        Date today = Date.today();
        Date startDate = today.toStartOfWeek();
        Date endDate   = startDate.addDays(6);

        List<Invoice_Line_Item__c> rawItems = [
            SELECT Name, Invoice_No__c, Ori_Plast_Invoice__r.Invoice_Number__c,
                   Ori_Plast_Invoice__r.Name, Ori_Plast_Invoice__r.Invoice_Date__c,
                   Ori_Plast_Invoice__r.CreatedDate, Ori_Plast_Invoice__r.Distributor__r.Name,
                   Ori_Plast_Invoice__r.Dealer_Name__c, Ori_Plast_Product_Name__c, SKU__c,
                   Ori_Plast_Product__r.Sub_Category_Picklist__c,
                   Ori_Plast_Product__r.Category_Picklist__c, Unit_of_Measure__c,
                   Quantity__c, Final_Price__c
            FROM Invoice_Line_Item__c
            WHERE Ori_Plast_Invoice__r.Distributor__c = :distributorId
            AND Ori_Plast_Invoice__r.CreatedDate >= :startDate
            AND Ori_Plast_Invoice__r.CreatedDate <= :endDate
            ORDER BY Ori_Plast_Invoice__r.CreatedDate DESC
            LIMIT 45000
        ];

        // Fully compatible String builder technique
        String csv = '';

        // Header
        csv += 'Invoice Number,Invoice Name,Invoice Line Item No,Invoice Date,Created Date,Distributor,Dealer Name,Product,SKU,Category,Quantity,Unit of Measure,Final Price\n';

        if (rawItems.isEmpty()) {
            return Blob.valueOf(csv);
        }

        Map<String, String> categoryLabelMap = buildCategoryLabelMap();

        for (Invoice_Line_Item__c line : rawItems) {

            String categoryLabel = categoryLabelMap.get(line.Ori_Plast_Product__r.Category_Picklist__c);

            csv += sanitize(line.Ori_Plast_Invoice__r.Invoice_Number__c) + ',';
            csv += sanitize(line.Ori_Plast_Invoice__r.Name) + ',';
            csv += sanitize(line.Name) + ',';
            csv += sanitize(String.valueOf(line.Ori_Plast_Invoice__r.Invoice_Date__c)) + ',';
            csv += sanitize(String.valueOf(line.Ori_Plast_Invoice__r.CreatedDate)) + ',';
            csv += sanitize(line.Ori_Plast_Invoice__r.Distributor__r.Name) + ',';
            csv += sanitize(line.Ori_Plast_Invoice__r.Dealer_Name__c) + ',';
            csv += sanitize(line.Ori_Plast_Product_Name__c) + ',';
            csv += sanitize(line.SKU__c) + ',';
            csv += sanitize(categoryLabel) + ',';
            csv += sanitize(String.valueOf(line.Quantity__c)) + ',';
            csv += sanitize(line.Unit_of_Measure__c) + ',';
            csv += sanitize(String.valueOf(line.Final_Price__c)) + '\n';
        }

        return Blob.valueOf(csv);
    }

    private static Map<String, String> buildCategoryLabelMap() {
        Map<String, String> mapLabels = new Map<String, String>();
        Schema.DescribeFieldResult d = OriPlast_Product__c.Category_Picklist__c.getDescribe();

        for (Schema.PicklistEntry entry : d.getPicklistValues()) {
            mapLabels.put(entry.getValue(), entry.getLabel());
        }
        return mapLabels;
    }

    private static String sanitize(String input) {
        if (input == null) return '';
        String val = input.replace(',', ' ');
        return val.replace('\n', ' ').replace('\r', ' ');
    }
}