objects/Invoice_Line_Item__c.object
<CustomObject>
    <fields>
        <fullName>CGST_Percentage__c</fullName>
        <description>This Field store CGST Percentage from Integration</description>
        <label>CGST Percentage</label>
        <precision>5</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>CGST__c</fullName>
        <description>This Field store CGST from Integration</description>
        <label>CGST</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <description>This Field store Description from Integration</description>
        <label>Description</label>
        <length>250</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Final_Price__c</fullName>
        <description>This Field store Final Price from Integration</description>
        <label>Final Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>IGST_Percentage__c</fullName>
        <description>This Field store IGST Percentage from Integration</description>
        <label>IGST Percentage</label>
        <precision>5</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>IGST__c</fullName>
        <description>This Field store IGST from Integration</description>
        <label>IGST</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Ori_Plast_Invoice__c</fullName>
        <label>Ori-Plast Invoice</label>
        <referenceTo>Invoice__c</referenceTo>
        <relationshipName>Ori_plast_Invoice_Line_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Quantity__c</fullName>
        <description>This Field store Quantity from Integration</description>
        <label>Quantity</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Rate__c</fullName>
        <label>Rate</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>SGST_Percentage__c</fullName>
        <description>This Field store SGST Percentage from Integration</description>
        <label>SGST Percentage</label>
        <precision>5</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>SGST__c</fullName>
        <description>This Field store SGST from Integration</description>
        <label>SGST</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>SKU__c</fullName>
        <label>Item Description</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Total_Discount_Percentage__c</fullName>
        <label>Total Discount %</label>
        <precision>5</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Unit_of_Measure__c</fullName>
        <description>This Field store Unit of Measure from Integration</description>
        <label>UOM</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>Invoice Line Item</label>
    <nameField>
        <displayFormat>ILN-{0000000}</displayFormat>
        <label>Invoice-Line-Item No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoice Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/InvLineItemRecCreationBatchController.cls
public without sharing class InvLineItemRecCreationBatchController {
    
    

    public static List<Invoice_Line_Item__c> createInvoiceLineItemRecords(List<TallyJsonDataObject.InvoiceDetails> invoiceDetailsList, Map<String, Id> invoiceExternalIdMap) {
        List<Invoice_Line_Item__c> lineItemRecordsToInsert = new List<Invoice_Line_Item__c>();
        
        for (TallyJsonDataObject.InvoiceDetails invoiceDetail : invoiceDetailsList) {
            Id invoiceId = invoiceExternalIdMap.get(invoiceDetail.InvoiceNumber);
            
            if (invoiceId != null && invoiceDetail.invoiceStatus != 'Cancelled') {
                for (TallyJsonDataObject.InvoiceLineItem lineItem : invoiceDetail.invoiceLineItems) {
                    Invoice_Line_Item__c lineItemRecord = new Invoice_Line_Item__c();
                    lineItemRecord.Ori_Plast_Invoice__c = invoiceId;
                    //lineItemRecord.Description__c = lineItem.description;
                    lineItemRecord.Quantity__c = lineItem.Quantity != 0 ? lineItem.Quantity : null;
                    lineItemRecord.Unit_of_Measure__c = lineItem.UnitofMeasure != 'null' ? lineItem.UnitofMeasure : null;
                    lineItemRecord.Rate__c = lineItem.Rate != 0 ? lineItem.Rate : null;
                    lineItemRecord.Total_Discount_Percentage__c = stringToDecimal(lineItem.TotalDiscountPercentage) != 0 ? stringToDecimal(lineItem.TotalDiscountPercentage) : null;
                    //lineItemRecord.CGST__c = stringToDecimal(lineItem.cgst);
                    //lineItemRecord.CGST_Percentage__c = stringToDecimal(lineItem.cgstPercentage);
                    //lineItemRecord.SGST__c = stringToDecimal(lineItem.sgst);
                    //lineItemRecord.SGST_Percentage__c = stringToDecimal(lineItem.sgstPercentage);
                    //lineItemRecord.IGST__c = stringToDecimal(lineItem.igst);
                    //lineItemRecord.IGST_Percentage__c = stringToDecimal(lineItem.igstPercentage);
                    lineItemRecord.Final_Price__c = lineItem.FinalPrice != 0 ? lineItem.FinalPrice : null;
                    lineItemRecord.SKU__c = lineItem.SKU != 'null' ? lineItem.SKU : null ;
                    
                    
                    lineItemRecordsToInsert.add(lineItemRecord);
                }
            } else {
                System.debug('Invoice External ID not found or Invoice Status is Cancelled for: ' + invoiceDetail.InvoiceNumber);
            }
        }
        //insertInvoiceLineitm(lineItemRecordsToInsert);
        
        return lineItemRecordsToInsert;
    }

   

    // ** Insert Invoice Line Item & Clear the list after insertion
    /*public static void insertInvoiceLineitm(List<Invoice_Line_Item__c> lineItemRecordsToInsert) {
        System.debug('lineItemRecordsToInsert INV++++++ : ' + lineItemRecordsToInsert);
       try {
         if (!lineItemRecordsToInsert.isEmpty()) {
            Database.SaveResult[] newInvoiceLineItemsList = Database.insert(lineItemRecordsToInsert,false);
            lineItemRecordsToInsert.clear();
        }
       } catch(Exception ex) {
        System.debug(ex.getMessage());
        CreateTransactionLog.log('Error', 'distributorIdentificationKeys', 'execute', ex.getMessage(), null,  null ,  ex.getStackTraceString(), null);
       }
    }*/

    // ** Method to convert String to Decimal, handling 'null'====
    public static Decimal stringToDecimal(Decimal value) {
        if (value != null && value != 0) {
            return value;
        } else {
            return null;
        }
    }   
}