objects/Order_Line_Item__c.object
<CustomObject>
    <fields>
        <fullName>CGST__c</fullName>
        <description>This Field store CGST Price (Price After Discount * CGST%)</description>
        <label>CGST</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Cash_Discount_CD__c</fullName>
        <description>This Field store Cash Discount ((Quantity*Unit Price)*Cash Discount %</description>
        <label>Cash Discount(CD)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Final_Price__c</fullName>
        <description>This Field store Final Price ((Quantity*Unit Price)-Total Discount )+CGST+SGST</description>
        <label>Final Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>OriPlast_Product_Unit_Price__c</fullName>
        <description>This field fetch Unit Price from related product</description>
        <formula>OriPlast_Product_Price__r.Unit_Price__c</formula>
        <label>OriPlast Product Unit Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Ori_Plast_Order__c</fullName>
        <description>Lookup with Ori-plast Order</description>
        <label>Ori-Plast Order</label>
        <referenceTo>Ori_Plast_Order__c</referenceTo>
        <relationshipLabel>Order-Line-Items</relationshipLabel>
        <relationshipName>Order_Line_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Ori_Plast_Product_Name__c</fullName>
        <description>This Field is used to show Ori-Plast Product name in place order LWC</description>
        <formula>Ori_Plast_Product__r.Name</formula>
        <label>Ori-Plast Product Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Ori_Plast_Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup with Ori-plast Product</description>
        <label>Ori-Plast Product</label>
        <referenceTo>OriPlast_Product__c</referenceTo>
        <relationshipLabel>Order-Line-Items</relationshipLabel>
        <relationshipName>Order_Line_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Price_After_Discount__c</fullName>
        <description>This Field store After Discount Price ((Quantity*Unit Price)-Trade Discount - Cash Discount)</description>
        <label>Price After Discount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Quantity__c</fullName>
        <description>This is for Product quantity</description>
        <label>Quantity</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>SGST__c</fullName>
        <description>This Field store SGST price (Price After Discount * SGST%)</description>
        <label>SGST</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Trade_Discount_TD__c</fullName>
        <description>This Field store Trade Discount ((Quantity*Unit Price)*Trade Discount %)</description>
        <label>Trade Discount(TD)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Unit_of_Measure__c</fullName>
        <label>Unit of Measure</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Order-Line-Item</label>
    <nameField>
        <displayFormat>OLN-{000000}</displayFormat>
        <label>Order-Line-Item No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Order-Line-Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Ori_Plast_Order__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <description>Ori-plast product Supplier</description>
        <inlineHelpText>The distributor account that generated the sales order.</inlineHelpText>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Ori-Plast Orders</relationshipLabel>
        <relationshipName>Ori_Plast_Orders</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Ori-Plast Order</label>
    <nameField>
        <displayFormat>ON-26-27-{000000}</displayFormat>
        <label>Ori-Plast Order No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Ori-Plast Orders</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/OriPlast_Product__c.object
<CustomObject>
    <fields>
        <fullName>Base_Unit_of_Measure__c</fullName>
        <description>This field is used for entering a unit of measurement adopted for a base quantity</description>
        <inlineHelpText>It is used for entering Base unit of measure.</inlineHelpText>
        <label>Base Unit of Measure</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Category_Picklist__c</fullName>
        <description>This is a picklist field for choosing type of Category for the customers who search for products.</description>
        <inlineHelpText>This is a picklist field for choosing type of category.</inlineHelpText>
        <label>Category</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>P1</fullName>
                    <label>PVC Pipe ASTM-D-1785, PVC ASTM (Schdule)</label>
                </value>
                <value>
                    <fullName>P2</fullName>
                    <label>PVC Grey pipes as per IS : 4985,UPVC IS 4985</label>
                </value>
                <value>
                    <fullName>P3</fullName>
                    <label>CASING &amp; PVC Casing Pipes as per IS : 12818</label>
                </value>
                <value>
                    <fullName>P4</fullName>
                    <label>PVC SCREEN &amp; PVC Screen Pipes as per IS : 12818</label>
                </value>
                <value>
                    <fullName>P5</fullName>
                    <label>PVC GARDEN HOSE PIPE</label>
                </value>
                <value>
                    <fullName>P6</fullName>
                    <label>PVC SWR pipes &amp; fittings as per IS:13592</label>
                </value>
                <value>
                    <fullName>P7</fullName>
                    <label>PVC Column Pipe</label>
                </value>
                <value>
                    <fullName>P8</fullName>
                    <label>PVC Submersible</label>
                </value>
                <value>
                    <fullName>P9</fullName>
                    <label>CPVC Pipe</label>
                </value>
                <value>
                    <fullName>PF</fullName>
                    <label>PVC Fittings</label>
                </value>
                <value>
                    <fullName>H1</fullName>
                    <label>HDPE Pipe IS 4984 (Black)</label>
                </value>
                <value>
                    <fullName>H2</fullName>
                    <label>HDPE Pipe IS 14333 (Black)</label>
                </value>
                <value>
                    <fullName>H3</fullName>
                    <label>GI STANDERD &amp; PLB Duct Pipe</label>
                </value>
                <value>
                    <fullName>H4</fullName>
                    <label>HDPE IS 4427 (Blue/Black)</label>
                </value>
                <value>
                    <fullName>H5</fullName>
                    <label>HDPE 4984-2016</label>
                </value>
                <value>
                    <fullName>HF</fullName>
                    <label>HDPE Fittings</label>
                </value>
                <value>
                    <fullName>DF</fullName>
                    <label>Direct Action Hand Pump Fittings</label>
                </value>
                <value>
                    <fullName>M1</fullName>
                    <label>MDPE Pipe &amp; MDPE IS 14885</label>
                </value>
                <value>
                    <fullName>M2</fullName>
                    <label>MDPE pipe &amp; MDPE IS 4427</label>
                </value>
                <value>
                    <fullName>SL</fullName>
                    <label>Solvent Cement</label>
                </value>
                <value>
                    <fullName>NI</fullName>
                    <label>PVC SWR pipes &amp; fittings (non-standard)</label>
                </value>
                <value>
                    <fullName>DP</fullName>
                    <label>Direct Action Hand Pump Set</label>
                </value>
                <value>
                    <fullName>H6</fullName>
                    <label>PPR</label>
                </value>
                <value>
                    <fullName>H7</fullName>
                    <label>HDPE Copper Wire</label>
                </value>
                <value>
                    <fullName>M3</fullName>
                    <label>PE PIPE(MDPE)</label>
                </value>
                <value>
                    <fullName>MF</fullName>
                    <label>MDPE Fittings</label>
                </value>
                <value>
                    <fullName>OF</fullName>
                    <label>OPVC Fittings</label>
                </value>
                <value>
                    <fullName>OP</fullName>
                    <label>OPVC Pipe</label>
                </value>
                <value>
                    <fullName>WT</fullName>
                    <label>WATER TANK and FITTINGS</label>
                </value>
                <value>
                    <fullName>TW</fullName>
                    <isActive>false</isActive>
                    <label>ASTM-D 1785 Push type White, Solvent Ciment Type</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>GST_Value__c</fullName>
        <description>This Field is used to calculate GST on flow</description>
        <formula>IF( GST_Group_Code__c  = &quot;G18.00&quot;, 18,  IF(GST_Group_Code__c  = &quot;G05.00&quot;, 5, 00) )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>GST Value</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Item_Disc_Group__c</fullName>
        <description>Here the discounts are defined for specific items or item groups.</description>
        <inlineHelpText>It is used for entering Item Discount Group</inlineHelpText>
        <label>Item Disc. Group</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Length_In_Meter__c</fullName>
        <description>This field will display the length of the product in meter</description>
        <formula>TEXT(VALUE(Length__c)/10)</formula>
        <label>Length (Meter)</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sub_Category_Picklist__c</fullName>
        <description>This is kind of picklist for choosing Sub Category of a product that is nested in another category.</description>
        <inlineHelpText>It is used for choosing Sub Category of a product.</inlineHelpText>
        <label>Sub Category</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Category_Picklist__c</controllingField>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>ASTM</fullName>
                </value>
                <value>
                    <fullName>CLASS1 (SDR11)</fullName>
                </value>
                <value>
                    <fullName>ISO 4427 Fittings</fullName>
                </value>
                <value>
                    <fullName>Male Thread</fullName>
                </value>
                <value>
                    <fullName>Pipe Grade PE 63</fullName>
                </value>
                <value>
                    <fullName>SDR 41</fullName>
                </value>
                <value>
                    <fullName>Single Socket</fullName>
                </value>
                <value>
                    <fullName>Pipe Grade PE 80</fullName>
                </value>
                <value>
                    <fullName>SDR 33</fullName>
                </value>
                <value>
                    <fullName>Bell End</fullName>
                </value>
                <value>
                    <fullName>CLASS2 (SDR 13.5)</fullName>
                </value>
                <value>
                    <fullName>Double Socket</fullName>
                </value>
                <value>
                    <fullName>IS 14333 Fittings</fullName>
                </value>
                <value>
                    <fullName>Male / Female Thread</fullName>
                </value>
                <value>
                    <fullName>UPVC</fullName>
                </value>
                <value>
                    <fullName>SDR 26</fullName>
                </value>
                <value>
                    <fullName>Pipe Grade PE 100</fullName>
                </value>
                <value>
                    <fullName>Plain End</fullName>
                </value>
                <value>
                    <fullName>Push Type</fullName>
                </value>
                <value>
                    <fullName>Sliding Socket</fullName>
                </value>
                <value>
                    <fullName>SWR</fullName>
                </value>
                <value>
                    <fullName>SDR 21</fullName>
                </value>
                <value>
                    <fullName>Cam Lock</fullName>
                </value>
                <value>
                    <fullName>CPVC</fullName>
                </value>
                <value>
                    <fullName>Flush Joint</fullName>
                </value>
                <value>
                    <fullName>SDR 17</fullName>
                </value>
                <value>
                    <fullName>LED &amp; TIN FREE</fullName>
                </value>
                <value>
                    <fullName>SDR 13.6</fullName>
                </value>
                <value>
                    <fullName>SDR 11</fullName>
                </value>
                <value>
                    <fullName>SDR 9</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Ori-Plast Product</label>
    <nameField>
        <label>Ori-PlastProduct Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Ori-Plast Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/EditOrderController.cls
public with sharing class EditOrderController {
    
    /* ================= FETCH ORDER LINES ================= */
    @AuraEnabled(cacheable=true)
    public static List<OrderLineDTO> getOrderLineItems(Id orderId) {
        List<OrderLineDTO> rows = new List<OrderLineDTO>();
        
        for (Order_Line_Item__c li : [
            SELECT Id,Name,Quantity__c,Final_Price__c,
            Price_After_Discount__c,
            OriPlast_Product_Unit_Price__c,
            CGST__c,
            SGST__c,Trade_Discount_TD__c,Cash_Discount_CD__c,
            Ori_Plast_Product_Name__c,
            Ori_Plast_Product__r.GST_Value__c,
            Ori_Plast_Product__r.Item_Disc_Group__c,
            Ori_Plast_Product__r.Base_Unit_of_Measure__c,
            Ori_Plast_Product__r.Length_In_Meter__c,
            Ori_Plast_Product__r.Id,
            Unit_of_Measure__c
            FROM Order_Line_Item__c WHERE Ori_Plast_Order__c = :orderId
            ]) {
            rows.add(new OrderLineDTO(li));
        }
        return rows;
    }
    
    @AuraEnabled(cacheable=true)
    public static List<Ori_Plast_Order__c> getOriPlastOrder(Id orderId) {
        return [
        SELECT Id, Name, Account__r.Name, Account__c FROM Ori_Plast_Order__c WHERE Id = :orderId LIMIT 1    
        ];
    }
    
    
    /* ================= DELETE ================= */
    
    @AuraEnabled
    public static String deleteOrderLineItems(List<Id> lineItemIds, Id orderId) {
        if (lineItemIds == null || lineItemIds.isEmpty()) {
            throw new AuraHandledException('No Order Line Items selected');
        }
        
        delete [SELECT Id FROM Order_Line_Item__c WHERE Id IN :lineItemIds];
        return 'SUCCESS';
    }
    
    public class OrderLineDTO {
        @AuraEnabled public Id id;
        @AuraEnabled public Decimal quantity;
        @AuraEnabled public Decimal finalPrice;
        @AuraEnabled public Decimal priceAfterDiscount;
        @AuraEnabled public Decimal unitPrice;
        @AuraEnabled public Decimal cgst;
        @AuraEnabled public Decimal sgst;
        @AuraEnabled public Decimal tradeDiscount;
        @AuraEnabled public Decimal cashDiscount;
        @AuraEnabled public String productName;
        @AuraEnabled public Decimal gstValue;
        @AuraEnabled public String itemDiscGroup;
        @AuraEnabled public String uom;
        @AuraEnabled public String lengthInMeter;
        @AuraEnabled public String unitOfMeasure;
        @AuraEnabled public Id productId;
        @AuraEnabled public String Unit_of_Measure;

        
        public OrderLineDTO(Order_Line_Item__c oli) {
            this.id = oli.Id;
            this.quantity = oli.Quantity__c;
            this.finalPrice = oli.Final_Price__c;
            this.productId = oli.Ori_Plast_Product__r.Id;
            this.priceAfterDiscount = oli.Price_After_Discount__c;
            this.unitPrice = oli.OriPlast_Product_Unit_Price__c;
            this.cgst = oli.CGST__c;
            this.sgst = oli.SGST__c;
            this.tradeDiscount = oli.Trade_Discount_TD__c;
            this.cashDiscount = oli.Cash_Discount_CD__c;
            this.productName = oli.Ori_Plast_Product_Name__c;
            this.gstValue = oli.Ori_Plast_Product__r.GST_Value__c;
            this.itemDiscGroup = oli.Ori_Plast_Product__r.Item_Disc_Group__c;
            this.uom = oli.Ori_Plast_Product__r.Base_Unit_of_Measure__c;
            this.lengthInMeter = oli.Ori_Plast_Product__r.Length_In_Meter__c;
            this.Unit_of_Measure = oli.Unit_of_Measure__c;
            // this.unitOfMeasure = oli.Ori_Plast_Product__r.Base_Unit_of_Measure__c;
            
        }
    }
    
    @AuraEnabled
    public static String updateOrderLineItems(List<Order_Line_Item__c> lines) {
        if (lines == null || lines.isEmpty()) {
            throw new AuraHandledException('No lines to update');
        }
        
        update lines;
        return 'SUCCESS';
    }
    
    
    public class OrderLineUpdate {
        @AuraEnabled public Id id;
        @AuraEnabled public Decimal quantity;
        @AuraEnabled public Decimal finalPrice;
        @AuraEnabled public Decimal priceAfterDiscount;
        @AuraEnabled public Decimal cgst;
        @AuraEnabled public Decimal sgst;
        @AuraEnabled public Decimal tradeDiscount;
        @AuraEnabled public Decimal cashDiscount;
    }
    
    @AuraEnabled(cacheable=true)
    public static List<OriPlast_Product__c> getProducts(
        Id accountId,
    String CategoryValue,
    String subCategoryValue,
    String identifierValue
    ) {
        String soql =
            'SELECT Id, Name, Category_Picklist__c, Sub_Category_Picklist__c, ' +
            'Identifire_Picklist__c, Size__c, Base_Unit_of_Measure__c ' +
            'FROM OriPlast_Product__c ' +
            'WHERE (Inactive_Product__c = false OR Inactive_Product__c = NULL)';
        
        // 🔐 Account → Inventory → Product
        if (accountId != null) {
            soql +=
                ' AND Id IN ( ' +
                ' SELECT Ori_Plast_Product__c FROM Inventory__c ' +
                ' WHERE Account__c = :accountId' +
                ')';
        }
        
        if (!String.isBlank(CategoryValue)) {
            soql += ' AND Category_Picklist__c = :CategoryValue';
        }
        
        if (!String.isBlank(subCategoryValue)) {
            soql += ' AND Sub_Category_Picklist__c = :subCategoryValue';
        }
        
        if (!String.isBlank(identifierValue)) {
            soql += ' AND Identifire_Picklist__c = :identifierValue';
        }
        
        return Database.query(soql);
    }
    
    
}