objects/Ori_Plast_Order__c.object
<CustomObject>
    <fields>
        <fullName>Days_of_created__c</fullName>
        <formula>TODAY() -   DATEVALUE(CreatedDate)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Days of created</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Order_Status__c</fullName>
        <description>This field state different stage of orders</description>
        <inlineHelpText>Order Status indicates various order stages.</inlineHelpText>
        <label>Order Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                    <color>#FF9900</color>
                    <default>true</default>
                    <label>Draft</label>
                </value>
                <value>
                    <fullName>Submitted</fullName>
                    <color>#33FFFF</color>
                    <label>Submitted</label>
                </value>
                <value>
                    <fullName>Received by Navision</fullName>
                    <color>#66FF99</color>
                    <label>Received by Business Central</label>
                </value>
                <value>
                    <fullName>Partially Delivered</fullName>
                    <color>#66CCCC</color>
                    <label>Partially Delivered</label>
                </value>
                <value>
                    <fullName>Delivered</fullName>
                    <color>#33CC00</color>
                    <label>Delivered</label>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                    <isActive>false</isActive>
                    <label>Cancelled</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Short_Close_Reason__c</fullName>
        <label>Short Close Reason</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Short_Closed__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Short Closed</label>
        <type>Checkbox</type>
    </fields>
    <label>Ori-Plast Order</label>
    <nameField>
        <displayFormat>ON-26-27-{000000}</displayFormat>
        <label>Ori-Plast Order No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Ori-Plast Orders</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/TransactionLog__c.object
<CustomObject>
    <fields>
        <fullName>Action__c</fullName>
        <description>Stores details regarding the method, action or processNode that this log was created from</description>
        <inlineHelpText>Stores details regarding the method, action or processNode that this log was created from</inlineHelpText>
        <label>Method or Action</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Message__c</fullName>
        <description>A description of the issue that has occurred.</description>
        <inlineHelpText>A description of the issue that has occurred.</inlineHelpText>
        <label>Message</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Process__c</fullName>
        <description>Stores the API name of either the Apex class, or Process that this log entry was created within.</description>
        <inlineHelpText>Stores the API name of either the Apex class, or Process that this log entry was created within.</inlineHelpText>
        <label>Class or Process</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Transaction Log</label>
    <nameField>
        <displayFormat>L-{000000000}</displayFormat>
        <label>Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Transaction Logs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/CheckingShortClose.cls
public class CheckingShortClose implements Database.Batchable<SObject>, Schedulable {
    
    //**Used in test class to simulate DML failure by injecting invalid field updates
    @TestVisible static Boolean forceDmlFailure = false;
    
    /*public Database.QueryLocator start(Database.BatchableContext BC) {  
        //**Query to fetch eligible draft orders older than 7 days
        //'SELECT Id, Days_of_created__c, Short_Closed__c, Short_Close_Reason__c, Order_Status__c FROM Ori_Plast_Order__c WHERE Days_of_created__c > 7 AND Order_Status__c = \'Draft\''
        //'SELECT Id, Days_of_created__c, Short_Closed__c, Short_Close_Reason__c, Order_Status__c FROM Ori_Plast_Order__c WHERE CreatedDate < LAST_N_DAYS:7 AND Order_Status__c = \'Draft\''
        return Database.getQueryLocator(
            'SELECT Id, Days_of_created__c, Short_Closed__c, Short_Close_Reason__c, Order_Status__c FROM Ori_Plast_Order__c WHERE LastModifiedDate < LAST_N_DAYS:7 AND Order_Status__c = \'Draft\''
        );
    }*/
    public Database.QueryLocator start(Database.BatchableContext BC) {

    String query =
        'SELECT Id, Days_of_created__c, Short_Closed__c, Short_Close_Reason__c, Order_Status__c ' +
        'FROM Ori_Plast_Order__c ' +
        'WHERE Order_Status__c = \'Draft\'';

        
        
        
    if (!Test.isRunningTest()) {
        query += ' AND LastModifiedDate < LAST_N_DAYS:7';
    }

        return Database.getQueryLocator(query);
    }
    
    public void execute(Database.BatchableContext BC, List<Ori_Plast_Order__c> orderRecord) {
        List<Ori_Plast_Order__c> ordersToUpdate = new List<Ori_Plast_Order__c>();
        List<TransactionLog__c> logsToInsert = new List<TransactionLog__c>();
        
        try {
            for (Ori_Plast_Order__c s : orderRecord) {
                if (forceDmlFailure) {
                    //**Inject invalid value to cause failure
                    s.put('Non_Existent_Field__c', 'force failure'); //**intentionally causes error
                } else {
                    s.Short_Closed__c = true;
                    s.Short_Close_Reason__c = Label.Short_Close_Reason;
                }
                ordersToUpdate.add(s);
            }
            
            //**Perform update and also capture any DML failures
            if (!ordersToUpdate.isEmpty()) {
                Database.SaveResult[] results = Database.update(ordersToUpdate, false);
                
                for (Integer i = 0; i < results.size(); i++) {
                    if (!results[i].isSuccess()) {
                        for (Database.Error err : results[i].getErrors()) {
                            TransactionLog__c tl  = new TransactionLog__c();
                            tl.Message__c = err.getMessage();
                            tl.Action__c = 'Execute';
                            tl.Process__c= 'CheckingShortClose' ;
                            logsToInsert.add(tl); 
                        }
                    }
                }
            }
        }catch (Exception e) {
            TransactionLog__c tl = new TransactionLog__c();
            tl.Message__c = e.getMessage();
            tl.Action__c = 'Execute';
            tl.Process__c = 'CheckingShortClose';
            logsToInsert.add(tl);
        }
        
        if (!logsToInsert.isEmpty()) {
            database.insert (logsToInsert);
        }
    }
    
    public void finish(Database.BatchableContext BC) {
        System.debug('Batch job finished.');
    }
    
    public void execute(SchedulableContext SC) {
        CheckingShortClose batch = new CheckingShortClose();
        Database.executeBatch(batch, 200);
    }
}